/* eslint-disable */
const printers = {
  printers: [
    { make: '101Hero', model: '101Hero' },
    { make: '3Dator GmbH', model: '3Dator' },
    { make: '3Deometry Innovations', model: '3DI D300' },
    { make: '3DTech', model: 'Semi-Professional' },
    { make: 'Abax 3D Technologies', model: 'Abax PRi3' },
    { make: 'Abax 3D Technologies', model: 'Abax PRi5' },
    { make: 'Abax 3D Technologies', model: 'Abax Titan' },
    { make: 'Alfawise', model: 'U20' },
    { make: 'Alfawise', model: 'U30' },
    { make: 'Kati Hal ARGE', model: 'Alya' },
    { make: 'Kati Hal ARGE', model: 'Alya NX' },
    { make: 'Anet', model: 'anet3d' },
    { make: 'Anet', model: 'A2' },
    { make: 'Anet', model: 'A2 Plus' },
    { make: 'Anet', model: 'A6' },
    { make: 'Anet', model: 'A8' },
    { make: 'Anet', model: 'A8 Plus' },
    { make: 'Anet', model: 'E10' },
    { make: 'Anet', model: 'E12' },
    { make: 'Anet', model: 'E16' },
    { make: 'Anet', model: 'ET4' },
    { make: 'Anet', model: 'ET4 Pro' },
    { make: 'Anet', model: 'ET4 X' },
    { make: 'Anet', model: 'ET5' },
    { make: 'Anet', model: 'ET5 X' },
    { make: 'AnkerMake', model: 'M5' },
    { make: 'Anycubic', model: '4Max' },
    { make: 'Anycubic', model: 'Chiron' },
    { make: 'Anycubic', model: 'i3 Mega' },
    { make: 'Anycubic', model: 'i3 Mega S/Pro' },
    { make: 'Anycubic', model: 'i3 Mega X' },
    { make: 'Anycubic', model: 'Kobra' },
    { make: 'Anycubic', model: 'Kobra Go' },
    { make: 'Anycubic', model: 'Kobra Max' },
    { make: 'Anycubic', model: 'Kossel' },
    { make: 'Anycubic', model: 'Kossel Linear Plus' },
    { make: 'Anycubic', model: 'Kossel Pulley' },
    { make: 'Anycubic', model: 'Mega Zero' },
    { make: 'Anycubic', model: 'Vyper' },
    { make: 'Sri Vignan Technologies', model: 'Arjun 300' },
    { make: 'Sri Vignan Technologies', model: 'Arjun Pro 300' },
    { make: 'Sri Vignan Technologies', model: 'Arjun Pro 300 Duplication' },
    { make: 'Sri Vignan Technologies', model: 'Arjun Pro 300 Mirror' },
    { make: 'Sri Vignan Technologies', model: 'Arjun 300 Duplication' },
    { make: 'Sri Vignan Technologies', model: 'Arjun 300 Mirror' },
    { make: 'Artillery', model: 'Genius' },
    { make: 'Artillery', model: 'Hornet' },
    { make: 'Artillery', model: 'Sidewinder X1' },
    { make: 'ATMAT sp. z o.o.', model: 'Asterion' },
    { make: 'ATMAT sp. z o.o.', model: 'Asterion HT' },
    { make: 'ATMAT sp. z o.o.', model: 'Galaxy 500' },
    { make: 'ATMAT sp. z o.o.', model: 'Galaxy 600' },
    { make: 'ATMAT sp. z o.o.', model: 'Signal Pro 300 v1' },
    { make: 'ATMAT sp. z o.o.', model: 'Signal Pro 300 v2' },
    { make: 'ATMAT sp. z o.o.', model: 'Signal Pro 400 v1' },
    { make: 'ATMAT sp. z o.o.', model: 'Signal Pro 400 v2' },
    { make: 'ATMAT sp. z o.o.', model: 'Signal Pro 500 v1' },
    { make: 'ATMAT sp. z o.o.', model: 'Signal Pro 500 v2' },
    { make: 'ATMAT sp. z o.o.', model: 'Signal XL' },
    { make: 'ATMAT sp. z o.o.', model: 'Signal XXL' },
    { make: 'ATMAT sp. z o.o.', model: 'Signal XXXL' },
    { make: 'Layer One', model: 'Atom 2' },
    { make: 'Layer One', model: 'Atom 3' },
    { make: 'Layer One', model: 'Atom 3 Lite' },
    { make: 'AtomStack', model: 'Cambrian Max E175' },
    { make: 'AtomStack', model: 'Cambrian Max E285' },
    { make: 'AtomStack', model: 'Cambrian Pro E175' },
    { make: 'AtomStack', model: 'Cambrian Pro E285' },
    { make: 'BeamUp', model: 'L' },
    { make: 'BeamUp', model: 'S' },
    { make: 'BFB', model: 'BFB' },
    { make: 'BIBO', model: 'Bibo 2 dual' },
    { make: 'Biqu', model: 'B1' },
    { make: 'Biqu', model: 'B1 ABL' },
    { make: 'Biqu', model: 'BX' },
    { make: 'Biqu', model: 'Hurakan' },
    { make: 'Blocks', model: 'One MKII' },
    { make: 'Blocks', model: 'One' },
    { make: 'Blocks', model: 'Pro S100' },
    { make: 'Blocks', model: 'Pro S30' },
    { make: 'Blocks', model: 'R21' },
    { make: 'Blocks', model: 'RD50' },
    { make: 'Blocks', model: 'RD50 - Duplication Mode' },
    { make: 'Blocks', model: 'RD50 - Mirror Mode' },
    { make: 'Blocks', model: 'Zero' },
    { make: 'BLV', model: 'MGN Cube 300' },
    { make: 'BLV', model: 'MGN Cube 350' },
    { make: 'BQ', model: 'Prusa i3 Hephestos' },
    { make: 'BQ', model: 'Hephestos 2' },
    { make: 'BQ', model: 'Prusa i3 Hephestos XL' },
    { make: 'BQ', model: 'Witbox' },
    { make: 'BQ', model: 'Witbox 2' },
    { make: 'Builder', model: 'Premium Large' },
    { make: 'Builder', model: 'Premium Medium' },
    { make: 'Builder', model: 'Premium Small' },
    { make: 'MaukCC', model: 'Cartesio' },
    { make: 'Cocoon Create', model: 'Cocoon Create' },
    { make: 'Cocoon Create', model: 'ModelMaker' },
    { make: 'Cocoon Create', model: 'Touch' },
    { make: 'Crazy3DPrint', model: 'CZ-300' },
    { make: 'Crazy3DPrint', model: 'CZ-300' },
    { make: 'Creality3D', model: 'CR-X' },
    { make: 'Creality3D', model: 'CR-10' },
    { make: 'Creality3D', model: 'CR-100' },
    { make: 'Creality3D', model: 'CR-10 Max' },
    { make: 'Creality3D', model: 'CR-10 Mini' },
    { make: 'Creality3D', model: 'CR-10S' },
    { make: 'Creality3D', model: 'CR-10S4' },
    { make: 'Creality3D', model: 'CR-10S5' },
    { make: 'Creality3D', model: 'CR-10 Smart' },
    { make: 'Creality3D', model: 'CR-10S Pro' },
    { make: 'Creality3D', model: 'CR-20' },
    { make: 'Creality3D', model: 'CR-20 Pro' },
    { make: 'Creality3D', model: 'CR-6 SE' },
    { make: 'Creality3D', model: 'Ender-2' },
    { make: 'Creality3D', model: 'Ender-3 / Ender-3 v2' },
    { make: 'Creality3D', model: 'Ender-3 Max' },
    { make: 'Creality3D', model: 'Ender-3 Pro' },
    { make: 'Creality3D', model: 'Ender-3 S1' },
    { make: 'Creality3D', model: 'Ender-3 S1 Plus' },
    { make: 'Creality3D', model: 'Ender-3 S1 Pro' },
    { make: 'Creality3D', model: 'Ender-4' },
    { make: 'Creality3D', model: 'Ender-5' },
    { make: 'Creality3D', model: 'Ender-5 Plus' },
    { make: 'Creality3D', model: 'Ender-6' },
    { make: 'Creality3D', model: 'Sermoon D1' },
    { make: 'Creality3D', model: 'Sermoon V1 & V1 Pro' },
    { make: 'Creasee', model: 'CS20' },
    { make: 'Creasee', model: 'CS30' },
    { make: 'Creasee', model: 'CS50s Pro' },
    { make: 'Creasee', model: 'Phoenix' },
    { make: 'Creasee', model: 'Skywalker' },
    { make: 'Ateam Ventures Co. Ltd.', model: 'Creatable D3' },
    { make: 'JOYPLACE CO., LTD.', model: 'cremaker common' },
    { make: 'JOYPLACE CO., LTD.', model: 'Cremaker M V1' },
    { make: 'JOYPLACE CO., LTD.', model: 'Cremaker M V2' },
    { make: 'JOYPLACE CO., LTD.', model: 'Cremaker S V1' },
    { make: 'Cubicon', model: 'Single' },
    { make: 'Cubicon', model: 'Style' },
    { make: 'Cubicon', model: 'Single Plus' },
    { make: 'Cubicon', model: 'Common' },
    { make: 'Cubicon', model: 'Dual Pro-A30' },
    { make: 'Cubicon', model: 'Style Neo-A22' },
    { make: 'Cubicon', model: 'Style Neo-A31' },
    { make: 'Cubicon', model: 'Style Plus-A15' },
    { make: 'Dagoma', model: 'Delta' },
    { make: 'Dagoma', model: 'Disco' },
    { make: 'Dagoma', model: 'DiscoEasy200' },
    { make: 'Dagoma', model: 'DiscoEasy200 Bicolor' },
    { make: 'Dagoma', model: 'DiscoUltimate' },
    { make: 'Dagoma', model: 'DiscoUltimate Bicolor' },
    { make: 'Dagoma', model: 'Magis' },
    { make: 'Dagoma', model: 'Neva' },
    { make: 'Dagoma', model: 'PRO 430 Bowden' },
    { make: 'Dagoma', model: 'PRO 430 Direct Drive' },
    { make: 'Dagoma', model: 'PRO 430 Dual' },
    { make: 'Dagoma', model: 'Sigma' },
    { make: 'Deltacomb 3D Printers', model: 'Deltacomb DC-20' },
    { make: 'Deltacomb 3D Printers', model: 'Deltacomb DC-20 Dual' },
    { make: 'Deltacomb 3D Printers', model: 'Deltacomb DC-20 Flux' },
    { make: 'Deltacomb 3D Printers', model: 'Deltacomb DC-21' },
    { make: 'Deltacomb 3D Printers', model: 'Deltacomb DC-21 Dual' },
    { make: 'Deltacomb 3D Printers', model: 'Deltacomb DC-21 Flux' },
    { make: 'Deltacomb 3D Printers', model: 'Deltacomb DC-30' },
    { make: 'Deltacomb 3D Printers', model: 'Deltacomb DC-30 Dual' },
    { make: 'Deltacomb 3D Printers', model: 'Deltacomb DC-30 Flux' },
    { make: 'Deltaprintr', model: 'Delta Go' },
    { make: 'Sri Vignan Technologies', model: 'Diytech 220' },
    { make: 'DXU', model: 'DXU' },
    { make: 'DXU', model: 'Dual' },
    { make: 'DXU', model: 'UMO+' },
    { make: 'DXU', model: 'UMO+  Dual' },
    { make: 'EasyArts', model: 'Ares' },
    { make: 'Eazao', model: 'Zero' },
    { make: 'ELEGOO', model: 'NEPTUNE' },
    { make: 'Elegoo', model: 'Neptune 2' },
    { make: 'Elegoo', model: 'Neptune 2D' },
    { make: 'ELEGOO', model: 'NEPTUNE 2S' },
    { make: 'ELEGOO', model: 'NEPTUNE 3' },
    { make: 'ELEGOO', model: 'NEPTUNE 3 Max' },
    { make: 'ELEGOO', model: 'NEPTUNE 3 Plus' },
    { make: 'ELEGOO', model: 'NEPTUNE 3 Pro' },
    { make: 'ELEGOO', model: 'NEPTUNE X' },
    { make: 'Eryone', model: 'ER20' },
    { make: 'Eryone', model: 'Thinker Series' },
    { make: 'Eryone', model: 'Thinker DirectDrive' },
    { make: 'Robokinetika', model: 'Erzay3D' },
    { make: 'FablabBcn', model: 'PastePrinter' },
    { make: 'Fabtotum', model: 'Personal Fabricator' },
    { make: 'FabX', model: 'Pro' },
    { make: 'Farm3D LLC', model: 'Farm 2' },
    { make: 'Farm3D LLC', model: 'Farm 2CE' },
    { make: 'Felix', model: 'Pro 2 Dual' },
    { make: 'Felix', model: 'Tec 4 Dual' },
    { make: 'Flashforge', model: 'Dreamer NX' },
    { make: 'Flashforge', model: 'Dreamer NX' },
    { make: 'Flsun', model: 'Q5' },
    { make: 'Flsun', model: 'QQ' },
    { make: 'Flsun', model: 'QQ-S' },
    { make: 'Flsun', model: 'Super Racer' },
    { make: 'Flsun', model: 'V400' },
    { make: 'Flying Bear', model: 'Ghost 4S' },
    { make: 'Flying Bear', model: 'Ghost 5' },
    { make: 'Folger Tech', model: 'FT-5' },
    { make: 'Fused Form', model: 'FF300' },
    { make: 'Fused Form', model: 'FF300 Doppia' },
    { make: 'Fused Form', model: 'FF600' },
    { make: 'Fused Form', model: 'FF600plus' },
    { make: 'Fused Form', model: 'FF600plus Doppia' },
    { make: 'Fused Form', model: 'FF600 Doppia' },
    { make: 'Fused Form', model: 'FFmini' },
    { make: 'Fused Form', model: 'FFSTD' },
    { make: 'Fused Form', model: 'FFSTD Doppia' },
    { make: 'Fusion3Design', model: 'Fusion3 F410' },
    { make: 'Geeetech', model: 'A10M' },
    { make: 'Geeetech', model: 'A10Pro' },
    { make: 'Geeetech', model: 'A10T' },
    { make: 'Geeetech', model: 'A20' },
    { make: 'Geeetech', model: 'A20M' },
    { make: 'Geeetech', model: 'A20T' },
    { make: 'Geeetech', model: 'A30M' },
    { make: 'Geeetech', model: 'A30Pro' },
    { make: 'Geeetech', model: 'A30T' },
    { make: 'Geeetech', model: 'E180' },
    { make: 'Geeetech', model: 'GiantArmD200' },
    { make: 'Geeetech', model: 'I3ProB' },
    { make: 'Geeetech', model: 'I3ProC' },
    { make: 'Geeetech', model: 'I3ProW' },
    { make: 'Geeetech', model: 'MeCreator' },
    { make: 'Geeetech', model: 'MeCreator2' },
    { make: 'Geeetech', model: 'MeDucer' },
    { make: 'Geeetech', model: 'Mizar' },
    { make: 'Geeetech', model: 'MizarM' },
    { make: 'Geeetech', model: 'MizarMax' },
    { make: 'Geeetech', model: 'MizarPro' },
    { make: 'Geeetech', model: 'MizarS' },
    { make: 'Geeetech', model: 'Thunder' },
    { make: 'gcreate', model: 'gMax 1.5 Plus' },
    { make: 'gCreate', model: 'gMax 1.5 Plus Dual Extruder' },
    { make: 'GooFoo', model: 'Goofoo Cube' },
    { make: 'GooFoo', model: 'Goofoo E-one' },
    { make: 'GooFoo', model: 'Goofoo Far' },
    { make: 'GooFoo', model: 'Goofoo Gemini' },
    { make: 'GooFoo', model: 'Goofoo Giant' },
    { make: 'GooFoo', model: 'Goofoo Max' },
    { make: 'GooFoo', model: 'Goofoo Mido' },
    { make: 'GooFoo', model: 'Goofoo Mini+' },
    { make: 'GooFoo', model: 'Goofoo Near' },
    { make: 'GooFoo', model: 'Goofoo Nova' },
    { make: 'GooFoo', model: 'Goofoo Open' },
    { make: 'GooFoo', model: 'Goofoo Plus' },
    { make: 'GooFoo', model: 'Goofoo Small' },
    { make: 'GooFoo', model: 'Goofoo T-one' },
    { make: 'GooFoo', model: 'Goofoo Tiny' },
    { make: 'GooFoo', model: 'Goofoo Tiny+' },
    { make: 'German RepRap', model: 'Neo' },
    { make: 'HardPrint', model: 'Hozo, Hozo' },
    { make: 'HardPrint', model: 'Hozo iX' },
    { make: 'HCTECH', model: '_HC300-M1&M1H' },
    { make: 'HCTECH', model: '_HC300-M2H' },
    { make: 'HCTECH', model: '_HC300-M3' },
    { make: 'Hellbot', model: 'Adonis' },
    { make: 'Hellbot', model: 'Hidra' },
    { make: 'Hellbot', model: 'Hidra Plus' },
    { make: 'Hellbot', model: 'Magna 2 230' },
    { make: 'Hellbot', model: 'Magna 2 230 dual' },
    { make: 'Hellbot', model: 'Magna 2 300' },
    { make: 'Hellbot', model: 'Magna 2 300 dual' },
    { make: 'Hellbot', model: 'Magna 2 400' },
    { make: 'Hellbot', model: 'Magna 2 400 dual' },
    { make: 'Hellbot', model: 'Magna 2 500' },
    { make: 'Hellbot', model: 'Magna 2 500 dual' },
    { make: 'Hellbot', model: 'Magna Dual' },
    { make: 'Hellbot', model: 'Magna 1' },
    { make: 'Hellbot', model: 'Magna SE' },
    { make: 'Beeverycreative', model: 'Hello Bee Prusa' },
    { make: 'Hybrid AM Systems', model: 'HMS434' },
    { make: 'eMotionTech', model: 'I3 Metal Motion' },
    { make: 'Ideagen3D', model: 'Sapphire Plus' },
    { make: 'Imade3D', model: 'JellyBOX Original' },
    { make: 'Imade3D', model: 'JellyBOX 2' },
    { make: 'Imade3D', model: 'imade3d_jellybox_root' },
    { make: 'Inat s.r.o.', model: 'Proton X Rail' },
    { make: 'Inat s.r.o.', model: 'Proton X Rod' },
    { make: 'Innovo', model: 'Inventor' },
    { make: 'JGAurora', model: 'A1' },
    { make: 'JGAurora', model: 'A3S' },
    { make: 'JGAurora', model: 'A5 & A5S' },
    { make: 'JGAurora', model: 'A6' },
    { make: 'JGAurora', model: 'JGMaker Magic' },
    { make: 'JGAurora', model: 'Z-603S' },
    { make: 'Fracktal', model: 'Julia' },
    { make: 'Kemiq', model: 'Q2 Beta' },
    { make: 'Kemiq', model: 'Q2 Gama' },
    { make: 'Key3D', model: 'Tyro' },
    { make: 'Kingroon', model: 'KP3' },
    { make: 'Kingroon', model: 'KP3S' },
    { make: 'KLEMA', model: '180' },
    { make: 'KLEMA', model: '250' },
    { make: 'KLEMA', model: '250 Pro' },
    { make: 'KLEMA', model: '250 Twin' },
    { make: 'KLEMA', model: '500' },
    { make: 'Koonovo', model: 'Elf' },
    { make: 'Koonovo', model: 'KN3 Idex' },
    { make: 'Koonovo', model: 'KN5 Idex' },
    { make: 'Koonovo', model: 'Pyramid' },
    { make: 'Sri Vignan Technologies', model: 'Kosher' },
    { make: 'Sri Vignan Technologies', model: 'Kosher Duplication' },
    { make: 'Sri Vignan Technologies', model: 'Kosher Mirror' },
    { make: 'Johann', model: 'Kossel Mini' },
    { make: 'Johann', model: 'Kossel Pro' },
    { make: 'Kati Hal ARGE', model: 'Kupido' },
    { make: 'Leapfrog', model: 'Bolt Pro' },
    { make: 'Leapfrog', model: 'Creatr HS' },
    { make: 'Leapfrog', model: 'Creatr HS XL' },
    { make: 'Liquid 3D', model: 'Liquid' },
    { make: 'Longer', model: 'Cube2' },
    { make: 'Longer', model: 'LK1' },
    { make: 'Longer', model: 'LK1 Plus' },
    { make: 'Longer', model: 'LK1 Pro' },
    { make: 'Longer', model: 'LK4' },
    { make: 'Longer', model: 'LK4 Pro' },
    { make: 'Longer', model: 'LK5' },
    { make: 'Longer', model: 'LK5 Pro' },
    { make: 'Lotmaxx', model: 'SC-10' },
    { make: 'Lotmaxx', model: 'SC-20' },
    { make: 'Lotmaxx', model: 'Shark' },
    {
      make: 'Fargo Additive Manufacturing Equipment 3D, LLC',
      model: 'Lulzbot Mini 2',
    },
    {
      make: 'Fargo Additive Manufacturing Equipment 3D, LLC',
      model: 'Lulzbot Mini 2 | SE | 0.5 mm',
    },
    {
      make: 'Fargo Additive Manufacturing Equipment 3D, LLC',
      model: 'Lulzbot Mini 2 | SL | 0.25 mm (Micro)',
    },
    {
      make: 'Fargo Additive Manufacturing Equipment 3D, LLC',
      model: 'Lulzbot TAZ Pro',
    },
    {
      make: 'Fargo Additive Manufacturing Equipment 3D, LLC',
      model: 'Lulzbot TAZ Pro Dual Extruder',
    },
    { make: 'Makeblock', model: 'mCreate' },
    { make: 'Makeit 3D', model: 'Makeit Pro-L' },
    { make: 'Makeit 3D', model: 'Makeit Pro-M' },
    { make: 'Makeit 3D', model: 'Makeit Pro-MX' },
    { make: 'MakerBot', model: 'Replicator' },
    { make: 'MakerGear', model: 'M2' },
    { make: 'Maker Made', model: '300x' },
    { make: 'Maker', model: 'Pegasus' },
    { make: 'Maker', model: 'Prusa Tairona i3' },
    { make: '3DMaker', model: 'Starter' },
    { make: 'Malyan', model: 'M180' },
    { make: 'Malyan', model: 'M200' },
    { make: 'Mankati', model: 'Fullscale XT Plus' },
    { make: 'Foehnsturm', model: 'Mark2 for Ultimaker2' },
    { make: 'Magicfirm', model: 'MBot3D Grid 2+' },
    { make: 'Magicfirm', model: 'MBot3D Grid 2+ Dual' },
    { make: 'Magicfirm', model: 'MBot3D Grid 4' },
    { make: 'Magicfirm', model: 'MBot3D Grid 4 Dual' },
    { make: 'Nophead', model: 'Mendel90' },
    { make: 'Mingda', model: '1000Pro' },
    { make: 'Mingda', model: '4H' },
    { make: 'Mingda', model: '600Pro' },
    { make: 'Mingda', model: '6H' },
    { make: 'Mingda', model: 'D2' },
    { make: 'Mingda', model: 'D3/Pro' },
    { make: 'Mingda', model: 'D4 Pro' },
    { make: 'Mingda', model: 'Magician Max' },
    { make: 'Mingda', model: 'Magician Pro' },
    { make: 'Mingda', model: 'Magician X' },
    { make: 'Mingda', model: 'Rock3/Pro' },
    { make: 'Mixware', model: 'Hyper S' },
    { make: 'Modix', model: 'V3 BIG-120X' },
    { make: 'Modix', model: 'V3 BIG-120Z' },
    { make: 'Modix', model: 'V3 BIG-180X' },
    { make: 'Modix', model: 'V3 BIG-40' },
    { make: 'Modix', model: 'V3 BIG-60' },
    { make: 'Modix', model: 'V3 BIG-Meter' },
    { make: 'Modix', model: 'V4 BIG-120X' },
    { make: 'Modix', model: 'V4 BIG-120Z' },
    { make: 'Modix', model: 'V4 BIG-180X' },
    { make: 'Modix', model: 'V4 BIG-60' },
    { make: 'Modix', model: 'V4 BIG-Meter' },
    { make: 'Monoprice', model: 'Select Mini V1' },
    { make: 'Monoprice', model: 'Select Mini V2 (E3D)' },
    { make: 'Monoprice', model: 'Ultimate' },
    { make: 'Monoprice', model: 'MP Mini Delta' },
    { make: 'Monoprice', model: 'MP Mini Delta V2' },
    { make: 'Naxe', model: 'nps' },
    { make: 'Nwa 3D LLC', model: 'Nwa3D A31' },
    { make: 'Nwa 3D LLC', model: 'Nwa3D A5' },
    { make: 'ORD Solutions', model: 'RoVa3D' },
    { make: 'PBR Research', model: 'PBR 3D Gen-I' },
    { make: 'Peopoly', model: 'Moai' },
    { make: 'Anycubic', model: 'Predator' },
    { make: 'Printrbot', model: 'Play' },
    { make: 'Printrbot', model: 'Play (Heated Bed)' },
    { make: 'Printrbot', model: 'Simple' },
    { make: 'Printrbot', model: 'Simple Metal Extended' },
    { make: 'Printrbot', model: "Simple Maker's Kit (1405)" },
    { make: 'Prusa3D', model: 'Prusa i3' },
    { make: 'Prusa3D', model: 'Prusa i3 Mk2' },
    { make: 'Prusa3D', model: 'Prusa i3 Mk3/Mk3s' },
    { make: 'Prusa3D', model: 'Prusa i3 xl' },
    { make: 'Punchtec', model: 'Connect XL' },
    { make: 'Raise3D', model: 'N2 Dual' },
    { make: 'Raise3D', model: 'N2 Plus Dual' },
    { make: 'Raise3D', model: 'N2 Plus Single' },
    { make: 'Raise3D', model: 'N2 Single' },
    { make: 'Renkforce', model: 'Basic 3' },
    { make: 'Renkforce', model: 'Cube One' },
    { make: 'Renkforce', model: 'Pro 3' },
    { make: 'Renkforce', model: 'Pro 6' },
    { make: 'Renkforce', model: 'Pro 6+' },
    { make: 'Renkforce', model: 'Pro7 Dual' },
    { make: 'Renkforce', model: 'RF100' },
    { make: 'Renkforce', model: 'RF100 V2' },
    { make: 'Renkforce', model: 'RF100 XL' },
    { make: 'Rigid3D', model: '2. Nesil' },
    { make: 'Rigid3D', model: '3. Nesil' },
    { make: 'Rigid3D', model: 'Hobby' },
    { make: 'Rigid3D', model: 'Mucit' },
    { make: 'Rigid3D', model: 'Mucit2' },
    { make: 'Rigid3D', model: 'Zero' },
    { make: 'Rigid3D', model: 'Zero2' },
    { make: 'Rigid3D', model: 'Zero3' },
    { make: 'RigidBot', model: 'RigidBot' },
    { make: 'RigidBot', model: 'Big' },
    { make: 'Robo 3D', model: 'R1' },
    { make: 'SecKit 3DP Design', model: 'SecKit SK-Go' },
    { make: 'SecKit 3DP Design', model: 'SecKit SK-Tank' },
    { make: 'SeeMeCNC', model: 'Artemis' },
    { make: 'SeeMeCNC', model: 'Rostock Max V3.2' },
    { make: 'Volumic', model: 'SH65' },
    { make: 'Skriware', model: '2' },
    { make: 'SnakeOilXY', model: 'SnakeOil Standard 180' },
    { make: 'SnakeOilXY', model: 'SnakeOil Standard 250' },
    { make: 'Snapmaker', model: '2' },
    { make: 'Snapmaker', model: '2 A150' },
    { make: 'Snapmaker', model: '2 A250' },
    { make: 'Snapmaker', model: '2 A350' },
    { make: 'Sovol 3D', model: 'Sovol SV01' },
    { make: 'Sovol 3D', model: 'Sovol SV01PRO' },
    { make: 'Sovol 3D', model: 'Sovol SV03' },
    { make: 'Sovol 3D', model: 'Sovol SV05' },
    { make: 'Sovol 3D', model: 'Sovol SV06' },
    { make: 'Stereotech LLC.', model: 'Stereotech Start' },
    { make: 'Stereotech LLC.', model: 'Stereotech STE320' },
    { make: 'eMotionTech', model: 'Strateo3D' },
    { make: 'Volumic', model: 'Stream20Dual MK2' },
    { make: 'Volumic', model: 'Stream20Pro MK2' },
    { make: 'Volumic', model: 'Stream30Dual MK2' },
    { make: 'Volumic', model: 'Stream30Pro MK3' },
    { make: 'Volumic', model: 'Stream30Pro MK2' },
    { make: 'Volumic', model: 'Stream30Ultra' },
    { make: 'Volumic', model: 'Stream30Ultra SC' },
    { make: 'Volumic', model: 'Stream30Ultra SC2' },
    { make: 'Structur3d.io', model: 'Discov3ry Complete' },
    { make: 'Sovol 3D', model: 'Sovol-SV01 (Legacy)' },
    { make: 'Sovol 3D', model: 'Sovol-SV02 (Legacy)' },
    { make: 'Sovol 3D', model: 'Sovol-SV03 (Legacy)' },
    { make: 'Syndaver3D', model: 'SyndaverAxi' },
    { make: 'Syndaver3D', model: 'SyndaverAxi2' },
    { make: 'TypeAMachines', model: 'Series 1 2014' },
    { make: 'tank_m', model: 'Tank M3' },
    { make: 'tank_m', model: 'Tank M3 Max' },
    { make: 'Tevo', model: 'Black Widow' },
    { make: 'Tevo', model: 'Tarantula' },
    { make: 'Tevo', model: 'Tarantula Pro' },
    { make: 'Tevo', model: 'Tornado' },
    { make: 'TinyBoy', model: 'E10/J10/L10/M10' },
    { make: 'TinyBoy', model: 'E16/L16/M16' },
    { make: 'TinyBoy', model: 'Fabrikator Mini 1.5' },
    { make: 'TinyBoy', model: 'RA20' },
    { make: 'Tizyx', model: 'Evy' },
    { make: 'Tizyx', model: 'Evy Dual' },
    { make: 'Tizyx', model: 'K25' },
    { make: 'Trimaker', model: 'Cosmos II' },
    { make: 'Trimaker', model: 'Nebula' },
    { make: 'Trimaker', model: 'Nebula Plus' },
    { make: 'Tronxy', model: 'D01' },
    { make: 'Tronxy', model: 'X5SA/X5ST/Pro/2E/D01 Plus' },
    { make: 'Tronxy', model: 'X5SA/X5ST/Pro/2E 400mm' },
    { make: 'Tronxy', model: 'X5SA/X5ST/Pro/2E 500mm' },
    { make: 'Tronxy', model: 'XY-2' },
    { make: 'Tronxy', model: 'XY-2 Pro/Pro 2E/XY3 SE' },
    { make: 'Tronxy', model: 'XY-3/Pro' },
    { make: 'Tronxy', model: 'XY-3 Pro V2' },
    { make: 'Two Trees', model: 'Bluer' },
    { make: 'Two Trees', model: 'Bluer Plus' },
    { make: 'Two Trees', model: 'Sapphire Plus' },
    { make: 'Two Trees', model: 'Sapphire Pro' },
    { make: 'uBuild-3D', model: 'Mr Bot 280' },
    { make: 'Ultimaker', model: 'Ultimaker B.V.' },
    { make: 'Ultimaker', model: '2' },
    { make: 'Ultimaker', model: '2 Extended' },
    { make: 'Ultimaker', model: '2 Extended with Olsson' },
    { make: 'Ultimaker', model: '2 Extended+' },
    { make: 'Ultimaker', model: '2 Go' },
    { make: 'Ultimaker', model: '2 with Olsson Block' },
    { make: 'Ultimaker', model: '2+' },
    { make: 'Ultimaker', model: '2+ Connect' },
    { make: 'Ultimaker', model: '3' },
    { make: 'Ultimaker', model: '3 Extended' },
    { make: 'Ultimaker', model: 'Original' },
    { make: 'Ultimaker', model: 'Original Dual Extrusion' },
    { make: 'Ultimaker', model: 'Original+' },
    { make: 'Ultimaker', model: 'S3' },
    { make: 'Ultimaker', model: 'S5' },
    { make: 'Ultimaker', model: 'S7' },
    { make: 'Unimatech', model: 'Uniqbot' },
    { make: 'Uni 3D', model: 'Uni 200' },
    { make: 'Uni 3D', model: 'Uni 250' },
    { make: 'Uni 3D', model: 'Uni 300' },
    { make: 'Uni 3D', model: 'Uni Mini' },
    { make: 'TheCoolTool', model: 'Uni-Print-3D' },
    { make: 'Velleman', model: 'Vertex Delta K8800' },
    { make: 'Velleman', model: 'Vertex K8400' },
    { make: 'Velleman', model: 'Vertex K8400 Dual' },
    { make: 'Velleman', model: 'Vertex K8600' },
    { make: 'Vivedino, Formbot', model: 'Vivedino T-REX 2+' },
    { make: 'Vivedino, Formbot', model: 'Vivedino T-REX 3' },
    { make: 'VoronDesign', model: 'Voron 0' },
    { make: 'VoronDesign', model: 'Voron2 250' },
    { make: 'VoronDesign', model: 'Voron2 300' },
    { make: 'VoronDesign', model: 'Voron2 350' },
    { make: 'VoronDesign', model: 'Voron2 Custom' },
    { make: 'VoronDesign', model: 'Voron Trident 250' },
    { make: 'VoronDesign', model: 'Voron Trident 300' },
    { make: 'VoronDesign', model: 'Voron Trident 350' },
    { make: 'VzBot', model: '235' },
    { make: 'VzBot', model: '330' },
    { make: 'VzBot', model: 'Custom' },
    { make: 'Wanhao', model: 'Duplicator 4S' },
    { make: 'Wanhao', model: 'Duplicator 6' },
    { make: 'Wanhao', model: 'Duplicator 6 Plus' },
    { make: 'Wanhao', model: 'Duplicator 9' },
    { make: 'Wanhao', model: 'Duplicator 5S' },
    { make: 'Wanhao', model: 'Duplicator 5S Mini' },
    { make: 'Wanhao', model: 'Duplicator i3' },
    { make: 'Wanhao', model: 'Duplicator i3 Mini' },
    { make: 'Wanhao', model: 'Duplicator i3 Plus' },
    { make: 'Weedo', model: 'X40' },
    { make: 'Winbo Smart Tech Co., Ltd.', model: 'Winbo Dragon(L)4' },
    { make: 'Winbo Smart Tech Co., Ltd.', model: 'Winbo Mini2' },
    { make: 'Winbo Smart Tech Co., Ltd.', model: 'Winbo Super Helper 105' },
    { make: 'Winbo Smart Tech Co., Ltd.', model: 'Winbo Super Helper 155' },
    { make: 'XYZprinting', model: 'da Vinci 1.0 Pro' },
    { make: 'XYZprinting', model: 'da Vinci Jr. 1.0A Pro' },
    { make: 'XYZprinting', model: 'da Vinci Jr. Pro Xe+' },
    { make: 'XYZprinting', model: 'da Vinci Jr. Pro X+' },
    { make: 'XYZprinting', model: 'da Vinci Jr. WiFi Pro' },
    { make: 'XYZprinting', model: 'da Vinci Pro EVO' },
    { make: 'XYZprinting', model: 'da Vinci Super' },
    { make: 'Z-Bolt Co.', model: 'Z-Bolt Classic' },
    { make: 'Z-Bolt Co.', model: 'Z-Bolt Plus' },
    { make: 'Zav Co., Ltd.', model: 'Zav Big' },
    { make: 'Zav Co., Ltd.', model: 'Zav Big+' },
    { make: 'Zav Co., Ltd.', model: 'Zav L Family Printer' },
    { make: 'Zav Co., Ltd.', model: 'Zav Max' },
    { make: 'Zav Co., Ltd.', model: 'Zav Pro' },
    { make: 'Zav Co., Ltd.', model: 'Zav Mini' },
    { make: 'Zone3D', model: 'Zone3d Printer' },
    { make: 'Magicfirm Europe', model: 'Zyyx Agile' },
  ],
};

export default printers;
