/* eslint-disable */
const printers = {
  printers: [
    { make: '101Hero', model: '101Hero' },
    { make: '3Dator GmbH', model: '3Dator' },
    { make: '3DTech', model: 'Semi-Professional' },
    { make: 'ABAX 3d Technologies', model: 'ABAX PRi3' },
    { make: 'ABAX 3d Technologies', model: 'ABAX PRi5' },
    { make: 'ABAX 3d Technologies', model: 'ABAX Titan' },
    { make: 'Alfawise', model: 'U20' },
    { make: 'Alfawise', model: 'U30' },
    { make: 'Kati Hal ARGE', model: 'ALYA' },
    { make: 'Kati Hal ARGE', model: 'ALYA NX' },
    { make: 'Anet', model: 'anet3d' },
    { make: 'Anet', model: 'A2' },
    { make: 'Anet', model: 'A2 PLUS' },
    { make: 'Anet', model: 'A6' },
    { make: 'Anet', model: 'A8' },
    { make: 'Anet', model: 'A8 PLUS' },
    { make: 'Anet', model: 'E10' },
    { make: 'Anet', model: 'E12' },
    { make: 'Anet', model: 'E16' },
    { make: 'Anet', model: 'ET4' },
    { make: 'Anet', model: 'ET4 PRO' },
    { make: 'Anet', model: 'ET4 X' },
    { make: 'Anet', model: 'ET5' },
    { make: 'Anet', model: 'ET5 X' },
    { make: 'Anycubic', model: '4Max' },
    { make: 'Anycubic', model: 'Chiron' },
    { make: 'Anycubic', model: 'i3 Mega' },
    { make: 'Anycubic', model: 'Kossel' },
    { make: 'Anycubic', model: 'Kossel Linear Plus' },
    { make: 'Anycubic', model: 'Kossel Pulley' },
    { make: 'Anycubic', model: 'Mega Zero' },
    { make: 'Artillery', model: 'Base Printer' },
    { make: 'Artillery', model: 'Genius' },
    { make: 'Artillery', model: 'Sidewinder X1' },
    { make: 'ATMAT sp. z o.o.', model: 'Asterion' },
    { make: 'ATMAT sp. z o.o.', model: 'Asterion HT' },
    { make: 'ATMAT sp. z o.o.', model: 'Galaxy 500' },
    { make: 'ATMAT sp. z o.o.', model: 'Galaxy 600' },
    { make: 'ATMAT sp. z o.o.', model: 'Signal Pro 300 v1' },
    { make: 'ATMAT sp. z o.o.', model: 'Signal Pro 300 v2' },
    { make: 'ATMAT sp. z o.o.', model: 'Signal Pro 400 v1' },
    { make: 'ATMAT sp. z o.o.', model: 'Signal Pro 400 v2' },
    { make: 'ATMAT sp. z o.o.', model: 'Signal Pro 500 v1' },
    { make: 'ATMAT sp. z o.o.', model: 'Signal Pro 500 v2' },
    { make: 'ATMAT sp. z o.o.', model: 'Signal Pro Base' },
    { make: 'ATMAT sp. z o.o.', model: 'Signal XL' },
    { make: 'ATMAT sp. z o.o.', model: 'Signal XXL' },
    { make: 'ATMAT sp. z o.o.', model: 'Signal XXXL' },
    { make: 'BeamUp', model: 'L' },
    { make: 'BeamUp', model: 'S' },
    { make: 'BFB', model: 'BFB' },
    { make: 'BIBO', model: '2 dual' },
    { make: 'BIQU', model: 'B1' },
    { make: 'BIQU', model: 'B1 ABL' },
    { make: 'BIQU', model: 'Biqu Base Printer' },
    { make: 'BLV', model: 'mgn Cube 300' },
    { make: 'BLV', model: 'mgn Cube 350' },
    { make: 'BLV', model: 'mgn Cube Base' },
    { make: 'BQ', model: 'Prusa i3 Hephestos' },
    { make: 'BQ', model: 'Hephestos 2' },
    { make: 'BQ', model: 'Prusa i3 Hephestos XL' },
    { make: 'BQ', model: 'Witbox' },
    { make: 'BQ', model: 'Witbox 2' },
    { make: 'Builder', model: 'Premium Large' },
    { make: 'Builder', model: 'Premium Medium' },
    { make: 'Builder', model: 'Premium Small' },
    { make: 'MaukCC', model: 'Cartesio' },
    { make: 'Cocoon Create', model: 'Cocoon Create' },
    { make: 'Cocoon Create', model: 'ModelMaker' },
    { make: 'Cocoon Create', model: 'Touch' },
    { make: 'Creality3D', model: 'CR-X' },
    { make: 'Creality3D', model: 'CR-10' },
    { make: 'Creality3D', model: 'CR-10 Max' },
    { make: 'Creality3D', model: 'CR-10 Mini' },
    { make: 'Creality3D', model: 'CR-10S' },
    { make: 'Creality3D', model: 'CR-10S4' },
    { make: 'Creality3D', model: 'CR-10S5' },
    { make: 'Creality3D', model: 'CR-10S Pro' },
    { make: 'Creality3D', model: 'CR-20' },
    { make: 'Creality3D', model: 'CR-20 Pro' },
    { make: 'Creality3D', model: 'CR-6 SE' },
    { make: 'Creality3D', model: 'Ender-2' },
    { make: 'Creality3D', model: 'Ender-3' },
    { make: 'Creality3D', model: 'Ender-3 Pro' },
    { make: 'Creality3D', model: 'Ender-4' },
    { make: 'Creality3D', model: 'Ender-5' },
    { make: 'Creality3D', model: 'Ender-5 Plus' },
    { make: 'Ateam Ventures Co. Ltd.', model: 'Creatable D3' },
    { make: 'Cubicon', model: 'Single' },
    { make: 'Cubicon', model: 'Style' },
    { make: 'Cubicon', model: 'Single Plus' },
    { make: 'Cubicon', model: 'Common' },
    { make: 'Cubicon', model: 'Dual Pro-A30' },
    { make: 'Cubicon', model: 'Style Neo-A22' },
    { make: 'Cubicon', model: 'Style Plus-A15' },
    { make: 'Dagoma', model: 'Delta' },
    { make: 'Dagoma', model: 'Disco' },
    { make: 'Dagoma', model: 'DiscoEasy200' },
    { make: 'Dagoma', model: 'DiscoEasy200 Bicolor' },
    { make: 'Dagoma', model: 'DiscoUltimate' },
    { make: 'Dagoma', model: 'DiscoUltimate Bicolor' },
    { make: 'Dagoma', model: 'Magis' },
    { make: 'Dagoma', model: 'Neva' },
    { make: 'Deltacomb 3D Printers', model: 'Deltacomb Base Printer' },
    { make: 'Deltacomb 3D Printers', model: 'Deltacomb DC-20' },
    { make: 'Deltacomb 3D Printers', model: 'Deltacomb DC-20 DUAL' },
    { make: 'Deltacomb 3D Printers', model: 'Deltacomb DC-20 FLUX' },
    { make: 'Deltacomb 3D Printers', model: 'Deltacomb DC-21' },
    { make: 'Deltacomb 3D Printers', model: 'Deltacomb DC-21 DUAL' },
    { make: 'Deltacomb 3D Printers', model: 'Deltacomb DC-21 FLUX' },
    { make: 'Deltacomb 3D Printers', model: 'Deltacomb DC-30' },
    { make: 'Deltacomb 3D Printers', model: 'Deltacomb DC-30 DUAL' },
    { make: 'Deltacomb 3D Printers', model: 'Deltacomb DC-30 FLUX' },
    { make: 'Deltaprintr', model: 'Delta Go' },
    { make: 'Sri Vignan Technologies', model: 'Diytech 220' },
    { make: 'DXU', model: 'DXU' },
    { make: 'DXU', model: 'Dual' },
    { make: 'EasyArts', model: 'Ares' },
    { make: 'Robokinetika', model: 'Erzay3D' },
    { make: 'FABtotum', model: 'Personal Fabricator' },
    { make: 'FabX', model: 'Pro' },
    { make: 'Felix', model: 'Pro 2 Dual' },
    { make: 'Felix', model: 'Tec 4 Dual' },
    { make: 'FLSUN', model: 'QQ' },
    { make: 'FLSUN', model: 'QQ-S' },
    { make: 'Flying Bear', model: 'Base Printer' },
    { make: 'Flying Bear', model: 'Ghost 4S' },
    { make: 'Flying Bear', model: 'Ghost 5' },
    { make: 'Folger Tech', model: 'FT-5' },
    { make: 'Fused Form', model: 'FF300' },
    { make: 'Fused Form', model: 'FF300 Doppia' },
    { make: 'Fused Form', model: 'FF600' },
    { make: 'Fused Form', model: 'FF600plus' },
    { make: 'Fused Form', model: 'FF600plus Doppia' },
    { make: 'Fused Form', model: 'FF600 Doppia' },
    { make: 'Fused Form', model: 'fusedform_base' },
    { make: 'Fused Form', model: 'fusedform_doppia_base' },
    { make: 'Fused Form', model: 'FFmini' },
    { make: 'Fused Form', model: 'FFSTD' },
    { make: 'Fused Form', model: 'FFSTD Doppia' },
    { make: 'Geeetech', model: 'A10' },
    { make: 'Geeetech', model: 'A10M' },
    { make: 'Geeetech', model: 'A10T' },
    { make: 'Geeetech', model: 'A20' },
    { make: 'Geeetech', model: 'A20M' },
    { make: 'Geeetech', model: 'A20T' },
    { make: 'Shenzhen Geeetech Technology', model: 'Geeetech A30' },
    { make: 'gcreate', model: 'gMax 1.5 Plus' },
    { make: 'gCreate', model: 'gMax 1.5 Plus Dual Extruder' },
    { make: 'German RepRap', model: 'Neo' },
    { make: 'Hellbot', model: 'Adonis' },
    { make: 'Hellbot', model: 'Magna DUAL' },
    { make: 'Hellbot', model: 'Magna 1' },
    { make: 'BEEVERYCREATIVE', model: 'Hello BEE Prusa' },
    { make: 'Hybrid AM Systems', model: 'HMS434' },
    { make: 'eMotionTech', model: 'I3 Metal Motion' },
    { make: 'ideagen3D', model: 'Sapphire Plus' },
    { make: 'IMADE3D', model: 'JellyBOX Original' },
    { make: 'IMADE3D', model: 'JellyBOX 2' },
    { make: 'IMADE3D', model: 'imade3d_jellybox_root' },
    { make: 'Innovo', model: 'INVENTOR' },
    { make: 'JGAurora', model: 'A1' },
    { make: 'JGAurora', model: 'A3S' },
    { make: 'JGAurora', model: 'A5 & A5S' },
    { make: 'JGAurora', model: 'JGMaker Magic' },
    { make: 'JGAurora', model: 'Z-603S' },
    { make: 'Fracktal', model: 'Julia' },
    { make: 'KEMIQ', model: 'Kemiq Q2 Beta' },
    { make: 'KEMIQ', model: 'Kemiq Q2 Gama' },
    { make: 'Key3D', model: 'Tyro' },
    { make: 'Koonovo', model: 'Base Printer' },
    { make: 'Koonovo', model: 'Elf' },
    { make: 'Koonovo', model: 'KN3 Idex' },
    { make: 'Koonovo', model: 'KN5 Idex' },
    { make: 'Koonovo', model: 'Pyramid' },
    { make: 'Johann', model: 'Kossel Mini' },
    { make: 'Johann', model: 'Kossel Pro' },
    { make: 'Kati Hal ARGE', model: 'KUPIDO' },
    { make: 'Leapfrog', model: 'Bolt Pro' },
    { make: 'Leapfrog', model: 'Creatr HS' },
    { make: 'Leapfrog', model: 'Creatr HS XL' },
    { make: 'Liquid 3D', model: 'Liquid' },
    { make: 'Lotmaxx', model: 'SC-10' },
    { make: 'Lotmaxx', model: 'SC-20' },
    { make: 'Lotmaxx', model: 'Shark' },
    { make: 'Makeblock', model: 'mCreate' },
    { make: 'MAKEiT 3D', model: 'MAKEiT Pro-L' },
    { make: 'MAKEiT 3D', model: 'MAKEiT Pro-M' },
    { make: 'MAKEiT 3D', model: 'MAKEiT Pro-MX' },
    { make: 'MakerBot', model: 'Replicator' },
    { make: 'makeR', model: 'Pegasus' },
    { make: 'makeR', model: 'Prusa Tairona i3' },
    { make: '3DMaker', model: 'Starter' },
    { make: 'Malyan', model: 'M180' },
    { make: 'Malyan', model: 'M200' },
    { make: 'Mankati', model: 'Fullscale XT Plus' },
    { make: 'Foehnsturm', model: 'Mark2 for Ultimaker2' },
    { make: 'Magicfirm', model: 'MBot3D Grid 2+' },
    { make: 'Magicfirm', model: 'MBot3D Grid 2+ Dual' },
    { make: 'Magicfirm', model: 'MBot3D Grid 4' },
    { make: 'Magicfirm', model: 'MBot3D Grid 4 Dual' },
    { make: 'Nophead', model: 'Mendel90' },
    { make: 'Monoprice', model: 'Select Mini V1' },
    { make: 'Monoprice', model: 'Select Mini V2 (E3D)' },
    { make: 'Monoprice', model: 'Ultimate' },
    { make: 'Monoprice', model: 'MP Mini Delta' },
    { make: 'NWA 3D LLC', model: 'NWA3D A31' },
    { make: 'NWA 3D LLC', model: 'NWA3D A5' },
    { make: 'ORD Solutions', model: 'RoVa3D' },
    { make: 'Peopoly', model: 'Moai' },
    { make: 'Anycubic', model: 'Predator' },
    { make: 'Printrbot', model: 'Play' },
    { make: 'Printrbot', model: 'Play (Heated Bed)' },
    { make: 'Printrbot', model: 'Simple' },
    { make: 'Printrbot', model: 'Simple Metal Extended' },
    { make: 'Printrbot', model: "Simple Maker's Kit (1405)" },
    { make: 'Prusa3D', model: 'Prusa i3' },
    { make: 'Prusa3D', model: 'Prusa i3 Mk2' },
    { make: 'Prusa3D', model: 'Prusa i3 Mk3/Mk3s' },
    { make: 'Prusa3D', model: 'Prusa i3 xl' },
    { make: 'Punchtec', model: 'Connect XL' },
    { make: 'Raise3D', model: 'N2 Dual' },
    { make: 'Raise3D', model: 'N2 Plus Dual' },
    { make: 'Raise3D', model: 'N2 Plus Single' },
    { make: 'Raise3D', model: 'N2 Single' },
    { make: 'Renkforce', model: 'RF100' },
    { make: 'Renkforce', model: 'RF100 V2' },
    { make: 'Renkforce', model: 'RF100 XL' },
    { make: 'Rigid3D', model: '2. Nesil' },
    { make: 'Rigid3D', model: '3. Nesil' },
    { make: 'Rigid3D', model: 'Base Printer' },
    { make: 'Rigid3D', model: 'Hobby' },
    { make: 'Rigid3D', model: 'Mucit' },
    { make: 'Rigid3D', model: 'Zero' },
    { make: 'Rigid3D', model: 'Zero2' },
    { make: 'RigidBot', model: 'RigidBot' },
    { make: 'RigidBot', model: 'Big' },
    { make: 'Robo 3D', model: 'R1' },
    { make: 'SeeMeCNC', model: 'Artemis' },
    { make: 'SeeMeCNC', model: 'Rostock Max V3.2' },
    { make: 'Skriware', model: '2' },
    { make: 'Stereotech LLC.', model: 'Stereotech START' },
    { make: 'Stereotech LLC.', model: 'Stereotech STE320' },
    { make: 'eMotionTech', model: 'Strateo3D' },
    { make: 'Structur3d.io', model: 'Discov3ry Complete' },
    { make: 'Sovol 3D', model: 'Sovol-SV01' },
    { make: 'Sovol 3D', model: 'Sovol-SV02' },
    { make: 'Syndaver3D', model: 'SyndaverAXI' },
    { make: 'typeamachines', model: 'Series 1 2014' },
    { make: 'Tevo', model: 'Black Widow' },
    { make: 'Tevo', model: 'Tarantula' },
    { make: 'Tevo', model: 'Tarantula Pro' },
    { make: 'Tevo', model: 'Tornado' },
    { make: 'TinyBoy', model: 'E10/J10/L10/M10' },
    { make: 'TinyBoy', model: 'E16/L16/M16' },
    { make: 'TinyBoy', model: 'Fabrikator Mini 1.5' },
    { make: 'TinyBoy', model: 'RA20' },
    { make: 'TiZYX', model: 'EVY' },
    { make: 'TiZYX', model: 'EVY Dual' },
    { make: 'TiZYX', model: 'K25' },
    { make: 'Tronxy', model: 'D01' },
    { make: 'Tronxy', model: 'Base Printer' },
    { make: 'Tronxy', model: 'X5SA/X5ST/Pro' },
    { make: 'Tronxy', model: 'X5SA/X5ST/Pro 400' },
    { make: 'Tronxy', model: 'X5SA/X5ST/Pro 500' },
    { make: 'Tronxy', model: 'XY-2' },
    { make: 'Tronxy', model: 'XY-2 Pro' },
    { make: 'Tronxy', model: 'XY-3' },
    { make: 'TwoTrees', model: 'Bluer' },
    { make: 'uBuild-3D', model: 'Mr Bot 280' },
    { make: 'Ultimaker', model: 'Ultimaker B.V.' },
    { make: 'Ultimaker', model: '2' },
    { make: 'Ultimaker', model: '2 Extended' },
    { make: 'Ultimaker', model: '2 Extended with Olsson' },
    { make: 'Ultimaker', model: '2 Extended+' },
    { make: 'Ultimaker', model: '2 Go' },
    { make: 'Ultimaker', model: '2 with Olsson Block' },
    { make: 'Ultimaker', model: '2+' },
    { make: 'Ultimaker', model: '2+ Connect' },
    { make: 'Ultimaker', model: '3' },
    { make: 'Ultimaker', model: '3 Extended' },
    { make: 'Ultimaker', model: 'Original' },
    { make: 'Ultimaker', model: 'Original Dual Extrusion' },
    { make: 'Ultimaker', model: 'Original+' },
    { make: 'Ultimaker', model: 'S3' },
    { make: 'Ultimaker', model: 'S5' },
    { make: 'Unimatech', model: 'Uniqbot' },
    { make: 'UNI 3D', model: 'UNI 200' },
    { make: 'UNI 3D', model: 'UNI 250' },
    { make: 'UNI 3D', model: 'UNI 300' },
    { make: 'UNI 3D', model: 'UNI Base Printer' },
    { make: 'UNI 3D', model: 'UNI MINI' },
    { make: 'TheCoolTool', model: 'UNI-PRINT-3D' },
    { make: 'Velleman', model: 'Vertex Delta K8800' },
    { make: 'Velleman', model: 'Vertex K8400' },
    { make: 'Velleman', model: 'Vertex K8400 Dual' },
    { make: 'Velleman', model: 'Vertex K8600' },
    { make: 'VORONDesign', model: 'VORON2 250' },
    { make: 'VORONDesign', model: 'VORON2 300' },
    { make: 'VORONDesign', model: 'VORON2 350' },
    { make: 'VORONDesign', model: 'VORON2 Base' },
    { make: 'VORONDesign', model: 'VORON2 Custom' },
    { make: 'Wanhao', model: 'Duplicator 4S' },
    { make: 'Wanhao', model: 'Duplicator 6' },
    { make: 'Wanhao', model: 'Duplicator 6 Plus' },
    { make: 'Wanhao', model: 'Duplicator 9' },
    { make: 'Wanhao', model: 'Duplicator 5S' },
    { make: 'Wanhao', model: 'Duplicator 5S Mini' },
    { make: 'Wanhao', model: 'Duplicator i3' },
    { make: 'Wanhao', model: 'Duplicator i3 Mini' },
    { make: 'Wanhao', model: 'Duplicator i3 Plus' },
    { make: 'Winbo Smart Tech Co., Ltd.', model: 'Winbo Dragon(L)4' },
    { make: 'Winbo Smart Tech Co., Ltd.', model: 'Winbo Mini2' },
    { make: 'Winbo Smart Tech Co., Ltd.', model: 'Winbo Super Helper 105' },
    { make: 'Winbo Smart Tech Co., Ltd.', model: 'Winbo Super Helper 155' },
    { make: 'Z-Bolt Co.', model: 'Z-Bolt Classic' },
    { make: 'Z-Bolt Co.', model: 'Z-Bolt Plus' },
    { make: 'ZAV Co., Ltd.', model: 'ZAV Base Printer' },
    { make: 'ZAV Co., Ltd.', model: 'ZAV BIG' },
    { make: 'ZAV Co., Ltd.', model: 'ZAV Big+' },
    { make: 'ZAV Co., Ltd.', model: 'ZAV L family printer' },
    { make: 'ZAV Co., Ltd.', model: 'ZAV MAX' },
    { make: 'ZAV Co., Ltd.', model: 'ZAV PRO' },
    { make: 'ZAV Co., Ltd.', model: 'ZAV mini' },
    { make: 'Zone3D', model: 'Zone3d Printer' },
    { make: 'Magicfirm Europe', model: 'ZYYX Agile' },
  ],
};

export default printers;
