import { TestBed } from '@angular/core/testing';
import { MatLegacyDialog as MatDialog } from '@angular/material/legacy-dialog';
import { ToastrService } from 'ngx-toastr';
import { PrusaSlicerFileParserService } from './file-parsers/prusa-slicer-file-parser.service';

import { GcodeFileParserService } from './gcode-file-parser.service';
import { LoggingService } from './logging.service';

describe('GcodeFileParserService', () => {
  let service: GcodeFileParserService;

  beforeEach(() => {
    const mockLoggingService = jasmine.createSpyObj<LoggingService>(
      'LoggingService',
      ['logEvent']
    );

    const mockPrusaSlicerService =
      jasmine.createSpyObj<PrusaSlicerFileParserService>(
        'PrusaSlicerFileParserService',
        ['parse']
      );

    const mockMatDialog = jasmine.createSpyObj<MatDialog>('MatDialog', [
      'open',
    ]);

    const mockToastr = jasmine.createSpyObj<ToastrService>('ToastrService', [
      'error',
    ]);

    TestBed.configureTestingModule({
      providers: [
        { provide: LoggingService, useValue: mockLoggingService },
        {
          provide: PrusaSlicerFileParserService,
          useValue: mockPrusaSlicerService,
        },
        { provide: MatDialog, useValue: mockMatDialog },
        { provide: ToastrService, useValue: mockToastr },
      ],
    });
    service = TestBed.inject(GcodeFileParserService);
  });

  it('should be created', () => {
    expect(service).toBeTruthy();
  });

  it('should call the parse method of PrusaSlicerFileParserService, when the gcode contains "generated by PrusaSlicer"', () => {
    const mockPrusaParser = TestBed.inject(PrusaSlicerFileParserService);

    const testGcode = `; generated by PrusaSlicer 2.2.0+win64 on 2020-11-21 at 14:50:39 UTC

; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

M201 X9000 Y9000 Z500 E10000 ; sets maximum accelerations, mm/sec^2
M203 X500 Y500 Z12 E120 ; sets maximum feedrates, mm/sec
M204 P1500 R1500 T1500 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2
M205 X10.00 Y10.00 Z0.20 E2.50 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
`;

    service.parse(testGcode);

    expect(mockPrusaParser.parse).toHaveBeenCalled();
  });
});
