import { Injectable } from '@angular/core';
import { MatDialog } from '@angular/material/dialog';

import { PrintDetail } from 'src/app/core/services/print.service';
import { ParserUnavailableDialogComponent } from 'src/app/shared/parser-unavailable-dialog/parser-unavailable-dialog.component';
import { PrusaSlicerFileParserService } from './file-parsers/prusa-slicer-file-parser.service';
import { LoggingService } from './logging.service';

/**
 * Parses Gcode text into a new PrintDetail object
 */
export interface GcodeNewPrintParser {
  parse(gcode: string): PrintDetail;
}

export enum SupportedGcodeParserSlicers {
  PrusaSlicer = 'Prusa Slicer',
}

@Injectable({
  providedIn: 'root',
})
export class GcodeFileParserService implements GcodeNewPrintParser {
  constructor(
    private readonly loggingService: LoggingService,
    private readonly prusaSlicerParser: PrusaSlicerFileParserService,
    private readonly dialog: MatDialog
  ) {}

  public getSupportedSlicers(): string[] {
    return Object.values(SupportedGcodeParserSlicers);
  }

  public parse(gcode: string): PrintDetail {
    const slicer: string = this.detectSlicerFromGcode(gcode);

    this.loggingService.logEvent('GcodeAnalyzed', {
      slicer,
    });

    console.log('Slicer Detected', slicer);

    switch (slicer) {
      case SupportedGcodeParserSlicers.PrusaSlicer:
        return this.prusaSlicerParser.parse(gcode);
      default:
        this.showParserUnavailableDialog();
        return null;
    }
  }
  showParserUnavailableDialog() {
    const dialogRef = this.dialog.open(ParserUnavailableDialogComponent, {
      minWidth: 300,
      maxWidth: 450,
      data: { supportedSlicers: this.getSupportedSlicers().join(', ') },
    });

    dialogRef.afterClosed().subscribe((result) => {});
  }
  private detectSlicerFromGcode(gcode: string): string {
    if (gcode.match(/generated by PrusaSlicer/)) {
      return SupportedGcodeParserSlicers.PrusaSlicer;
    }
    return 'unknown';
  }
}
