import { Injectable } from '@angular/core';

import { PrintDetail } from 'src/app/core/services/print.service';
import { PrusaSlicerFileParserService } from './file-parsers/prusa-slicer-file-parser.service';
import { LoggingService } from './logging.service';

/**
 * Parses Gcode text into a new PrintDetail object
 */
export interface GcodeNewPrintParser {
  parse(gcode: string): PrintDetail;
}

@Injectable({
  providedIn: 'root',
})
export class GcodeFileParserService implements GcodeNewPrintParser {
  constructor(
    private readonly loggingService: LoggingService,
    private readonly prusaSlicerParser: PrusaSlicerFileParserService
  ) {}

  public parse(gcode: string): PrintDetail {
    const slicer: string = this.detectSlicerFromGcode(gcode);

    this.loggingService.logEvent('GcodeAnalyzed', {
      slicer,
    });

    console.log('Slicer Detected', slicer);

    switch (slicer) {
      case 'PrusaSlicer':
        return this.prusaSlicerParser.parse(gcode);
      default:
        return null;
    }
  }
  private detectSlicerFromGcode(gcode: string): string {
    if (gcode.match(/generated by PrusaSlicer/)) {
      return 'PrusaSlicer';
    }
    return 'unknown';
  }
}
