import { Injectable } from '@angular/core';
import { MatDialog } from '@angular/material/dialog';
import { ToastrService } from 'ngx-toastr';

import { PrintDetail } from 'src/app/core/services/print.service';
import { GcodeViewerModalComponent } from 'src/app/shared/gcode-viewer-modal/gcode-viewer-modal.component';
import { ParserUnavailableDialogComponent } from 'src/app/shared/parser-unavailable-dialog/parser-unavailable-dialog.component';
import { PrusaSlicerFileParserService } from './file-parsers/prusa-slicer-file-parser.service';
import { LoggingService } from './logging.service';

/**
 * Parses Gcode text into a new PrintDetail object
 */
export interface GcodeNewPrintParser {
  /**
   * Parse PrintDetails from gcode
   * @param gcode The contents of a gcode file
   * @param fileName Optional file name of the gcode file
   */
  parse(gcode: string, fileName?: string): Promise<PrintDetail>;
}

export enum SupportedGcodeParserSlicers {
  PrusaSlicer = 'Prusa Slicer',
}

@Injectable({
  providedIn: 'root',
})
export class GcodeFileParserService implements GcodeNewPrintParser {
  constructor(
    private readonly loggingService: LoggingService,
    private readonly prusaSlicerParser: PrusaSlicerFileParserService,
    private readonly dialog: MatDialog,
    private readonly toastrService: ToastrService
  ) {}

  public getSupportedSlicers(): string[] {
    return Object.values(SupportedGcodeParserSlicers);
  }

  public async parse(gcode: string, fileName?: string): Promise<PrintDetail> {
    const slicer: string = this.detectSlicerFromGcode(gcode);

    this.loggingService.logEvent('GcodeAnalyzed', {
      slicer,
    });

    try {
      switch (slicer) {
        case SupportedGcodeParserSlicers.PrusaSlicer:
          return this.prusaSlicerParser.parse(gcode);
        default:
          const result = this.showGenericGcodeViewerModal(gcode, fileName);

          return result || null;
      }
    } catch (e: unknown) {
      this.toastrService.error(
        'An error occurred while parsing gcode, unable to extract settings.',
        'Error'
      );
      return null;
    }
  }
  GcodeViewerModalComponent;

  async showGenericGcodeViewerModal(
    gcode: string,
    fileName?: string
  ): Promise<PrintDetail> {
    return new Promise((resolve, reject) => {
      const dialogRef = this.dialog.open(GcodeViewerModalComponent, {
        disableClose: true,
        minWidth: 300,
        maxWidth: 450,
        data: { gcode: gcode, fileName: fileName },
      });

      dialogRef.afterClosed().subscribe((result) => {
        resolve(result);
      });
    });
  }

  showParserUnavailableDialog() {
    const dialogRef = this.dialog.open(ParserUnavailableDialogComponent, {
      minWidth: 300,
      maxWidth: 450,
      data: { supportedSlicers: this.getSupportedSlicers().join(', ') },
    });

    dialogRef.afterClosed().subscribe((result) => {});
  }
  private detectSlicerFromGcode(gcode: string): string {
    if (gcode.match(/generated by PrusaSlicer/)) {
      return SupportedGcodeParserSlicers.PrusaSlicer;
    }
    return 'unknown';
  }
}
