# Nightly build to run dependency checks
pr: none

trigger: none

schedules:
- cron: "0 0 * * *"
  displayName: 'Daily Midnight Build'
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'Npm Install And Build'

- script: |
    npm audit
  displayName: 'Npm Audit'
  continueOnError: true

- task: WhiteSource Bolt@20
  displayName: 'WhiteSource Bolt'
