/* eslint-disable */
// prettier-ignore
// Header + settings tail of an OrcaSlicer 2.2.0 export with three slots, the
// middle one unused. No toolpath — the parsers never read it.
export const ORCA_TWO_FILAMENT_GCODE = `; HEADER_BLOCK_START
; generated by OrcaSlicer 2.2.0 on 2025-01-01 at 10:00:00
; total layer number: 50
; model printing time: 58m 3s; total estimated time: 1h 2m 3s
; filament used [mm] = 1234.56, 0.00, 567.80
; filament used [g] = 3.68, 0.00, 1.69
; HEADER_BLOCK_END
G28
; CONFIG_BLOCK_START
; bottom_shell_layers = 3
; draft_shield = disabled
; filament_colour = #FF0000;#00FF00;#0000FF
; filament_density = 1.24,1.24,1.27
; filament_diameter = 1.75,1.75,1.75
; filament_type = PLA;PLA;PETG
; layer_height = 0.2
; ooze_prevention = 0
; print_settings_id = 0.20mm Standard @BBL X1C
; printer_settings_id = Bambu Lab X1 Carbon 0.4 nozzle
; sparse_infill_density = 15%
; sparse_infill_pattern = grid
; spiral_mode = 0
; support_filament = 0
; top_shell_layers = 4
; wall_loops = 2
; CONFIG_BLOCK_END
`;
