/* eslint-disable */
// prettier-ignore
// Header + settings tail of a PrusaSlicer 2.9.2 MK4S + MMU3 export using two of
// five slots. No toolpath.
export const PRUSA_MMU_TWO_SLOTS_GCODE = `; generated by PrusaSlicer 2.9.2+win64 on 2025-06-01 at 12:00:00 UTC

; external perimeters extrusion width = 0.45mm
; filament used [mm] = 2100.12, 0.00, 0.00, 900.55, 0.00
; filament used [cm3] = 5.05, 0.00, 0.00, 2.17, 0.00
; filament used [g] = 6.26, 0.00, 0.00, 2.75, 0.00
; total filament used [g] = 9.01
; estimated printing time (normal mode) = 1h 15m 30s
; estimated printing time (silent mode) = 1h 20m 0s

; prusaslicer_config = begin
; bottom_solid_layers = 4
; draft_shield = disabled
; fill_density = 15%
; fill_pattern = gyroid
; filament_colour = #FF8000;#000000;#000000;#0000FF;#000000
; filament_density = 1.24,1.24,1.24,1.27,1.24
; filament_diameter = 1.75,1.75,1.75,1.75,1.75
; filament_type = PLA;PLA;PLA;PETG;PLA
; layer_height = 0.2
; ooze_prevention = 0
; perimeters = 2
; print_settings_id = 0.20mm QUALITY @MK4S
; printer_settings_id = Original Prusa MK4S MMU3
; spiral_vase = 0
; support_material = 0
; top_solid_layers = 5
; prusaslicer_config = end
`;
