import { TestBed } from '@angular/core/testing';

import { PrusaSlicerFileParserService } from './prusa-slicer-file-parser.service';
import { PRUSA_MMU_TWO_SLOTS_GCODE } from '../fixtures/prusa-mmu-two-slots.fixture';

describe('PrusaSlicerFileParserService', () => {
  let service: PrusaSlicerFileParserService;

  beforeEach(() => {
    TestBed.configureTestingModule({});
    service = TestBed.inject(PrusaSlicerFileParserService);
  });

  it('should be created', () => {
    expect(service).toBeTruthy();
  });

  it('should parse the estimated print time using the normal mode when estimation exist in the gcode', async () => {
    const testGcode = `; total filament used [g] = 0.0
; total filament cost = 0.0
; estimated printing time (normal mode) = 1h 00m 00s
; estimated printing time (silent mode) = 1h 26m 53s`;
    const expectedEstPrintTime = 3600;

    const actual = await service.parse(testGcode);

    expect(actual.estimatedPrintTimeInSeconds).toBe(expectedEstPrintTime);
  });

  it('should set the estimated print time to undefined when no estimations exist in the gcode', async () => {
    const testGcodeWithoutEstimations = `; total filament used [g] = 0.0
    ; total filament cost = 0.0`;

    const actual = await service.parse(testGcodeWithoutEstimations);

    expect(actual.estimatedPrintTimeInSeconds).toBeUndefined();
  });
  describe('estimateFilamentUsageInMg', () => {
    it('should convert the reported gram total to milligrams when the slicer provides one', () => {
      const testGcode = `; total filament used [g] = 12.5`;

      expect(service.estimateFilamentUsageInMg(testGcode)).toBe(12500);
    });

    it('should compute the weight from length and diameter when no gram total is reported', () => {
      const testGcode = `; total filament used [g] = 0.0
; filament_type = PLA
; filament_diameter = 1.75
; filament used [mm] = 1000`;

      const actual = service.estimateFilamentUsageInMg(testGcode);

      expect(actual).toBeGreaterThan(0);
    });

    it('should return undefined for a material it has no density for', () => {
      const testGcode = `; total filament used [g] = 0.0
; filament_type = TPU
; filament_diameter = 1.75
; filament used [mm] = 1000`;

      expect(service.estimateFilamentUsageInMg(testGcode)).toBeUndefined();
    });

    it('should compute Nylon from its density (#100)', () => {
      const testGcode = `; total filament used [g] = 0.0
; filament_type = Nylon
; filament_diameter = 1.75
; filament used [mm] = 1000`;

      expect(service.estimateFilamentUsageInMg(testGcode)).toBe(2549);
    });

    it('should return undefined when the diameter is missing', () => {
      const testGcode = `; total filament used [g] = 0.0
; filament_type = PLA
; filament used [mm] = 1000`;

      expect(service.estimateFilamentUsageInMg(testGcode)).toBeUndefined();
    });

    it('should return undefined when the filament length is missing', () => {
      const testGcode = `; total filament used [g] = 0.0
; filament_type = PLA
; filament_diameter = 1.75`;

      expect(service.estimateFilamentUsageInMg(testGcode)).toBeUndefined();
    });

    it('should return undefined when the diameter or filament length is zero', () => {
      const zeroDiameter = `; total filament used [g] = 0.0
; filament_type = PLA
; filament_diameter = 0
; filament used [mm] = 1000`;
      const zeroLength = `; total filament used [g] = 0.0
; filament_type = PLA
; filament_diameter = 1.75
; filament used [mm] = 0`;

      expect(service.estimateFilamentUsageInMg(zeroDiameter)).toBeUndefined();
      expect(service.estimateFilamentUsageInMg(zeroLength)).toBeUndefined();
    });
  });
});

describe('PrusaSlicerFileParserService multi-material', () => {
  let service: PrusaSlicerFileParserService;

  beforeEach(() => {
    TestBed.configureTestingModule({});
    service = TestBed.inject(PrusaSlicerFileParserService);
  });

  it('emits one usage row per used slot', async () => {
    const print = await service.parse(PRUSA_MMU_TWO_SLOTS_GCODE);
    expect(print.filamentUsage.length).toBe(2);
    expect(print.filamentUsage[0].estimatedLengthInM).toBe(2.1);
    expect(print.filamentUsage[0].estimatedAmountMg).toBe(6260);
    expect(print.filamentUsage[0].notes).toBe('Slot 1 · #FF8000 · PLA');
    expect(print.filamentUsage[1].estimatedLengthInM).toBe(0.901);
    expect(print.filamentUsage[1].notes).toBe('Slot 4 · #0000FF · PETG');
    expect(print.estimatedPrintTimeInSeconds).toBe(4530);
  });

  it('keeps the notes text unchanged', async () => {
    const print = await service.parse(PRUSA_MMU_TWO_SLOTS_GCODE);
    expect(print.notes).toBe(`Print Settings:
Layer Height: 0.2mm
Top Layer Count: 5
Bottom Layer Count: 4
Perimeters: 2
Infill: 15%
Infill Pattern: gyroid
Support: No Supports
Print Setting Config: 0.20mm QUALITY @MK4S
Printer Config: Original Prusa MK4S MMU3`);
  });

  it('detects the PrusaSlicer marker', () => {
    expect(service.detect('; generated by PrusaSlicer 2.9.2')).toBeTrue();
  });
});
