import { Injectable } from '@angular/core';
import { GcodeParserBase } from '../core/gcode-parser-base';
import { GcodeSettings, SPACED_EQUALS } from '../core/gcode-settings';

const PRUSA_SETTING_KEYS: readonly string[] = [
  'spiral_vase',
  'layer_height',
  'top_solid_layers',
  'bottom_solid_layers',
  'perimeters',
  'fill_density',
  'fill_pattern',
  'support_material',
  'support_material_buildplate_only',
  'ooze_prevention',
  'draft_shield',
  'print_settings_id',
  'printer_settings_id',
];

@Injectable({
  providedIn: 'root',
})
export class PrusaSlicerFileParserService extends GcodeParserBase {
  readonly slicerName = 'Prusa Slicer';
  readonly settingsOptions = SPACED_EQUALS;
  readonly settingKeys = PRUSA_SETTING_KEYS;
  // PrusaSlicer writes the per-slot list under "filament used [g]" and the
  // sum under "total filament used [g]"; the sum is what the old parser read.
  protected override readonly filamentWeightKey = 'total filament used [g]';

  detect(gcode: string): boolean {
    return /^\s*;\s*generated by PrusaSlicer/m.test(gcode);
  }

  protected buildNotes(settings: GcodeSettings): string {
    let notes = '';
    const spiralVaseModeEnabled = settings.getNumber('spiral_vase') === 1;

    const layerHeight = settings.getNumber('layer_height');
    if (layerHeight) {
      notes += `Layer Height: ${layerHeight}mm\n`;
    }

    const topLayers = settings.getNumber('top_solid_layers');
    if (topLayers) {
      notes += `Top Layer Count: ${topLayers}\n`;
    }

    const bottomLayers = settings.getNumber('bottom_solid_layers');
    if (bottomLayers) {
      notes += `Bottom Layer Count: ${bottomLayers}\n`;
    }

    const perimeters = settings.getNumber('perimeters');
    if (perimeters) {
      notes += `Perimeters: ${perimeters}\n`;
    }

    const infillDensity = settings.get('fill_density');
    if (infillDensity !== '') {
      notes += `Infill: ${infillDensity}\n`;
      const infillPattern = settings.get('fill_pattern');
      if (infillPattern !== '') {
        notes += `Infill Pattern: ${infillPattern}\n`;
      }
    }

    if (settings.getNumber('support_material') === 1) {
      const buildplateOnly =
        settings.getNumber('support_material_buildplate_only') === 1;
      const supportType = buildplateOnly ? 'Touching Buildplate' : 'Everywhere';
      notes += `Support: Enabled ${supportType}`.trim() + '\n';
    } else {
      notes += 'Support: No Supports\n';
    }

    if (spiralVaseModeEnabled) {
      notes += 'Spiral Vase Mode: Enabled\n';
    }

    if (settings.getNumber('ooze_prevention') === 1) {
      notes += 'Ooze Prevention: Enabled\n';
    }

    if (settings.getNumber('draft_shield') === 1) {
      notes += 'Draft Shield: Enabled\n';
    }

    const settingId = settings.get('print_settings_id');
    if (settingId !== '') {
      notes += `Print Setting Config: ${settingId}\n`;
    }
    const printerConfigId = settings.get('printer_settings_id');
    if (printerConfigId !== '') {
      notes += `Printer Config: ${printerConfigId}\n`;
    }

    notes = notes.trim();
    if (notes !== '') {
      notes = 'Print Settings:\n' + notes;
    }
    return notes;
  }
}
