import { RenderMode, ServerRoute } from '@angular/ssr';

export const serverRoutes: ServerRoute[] = [
  { path: '', renderMode: RenderMode.Prerender },
  { path: 'cura', renderMode: RenderMode.Prerender },
  { path: 'prusaslicer', renderMode: RenderMode.Prerender },
  { path: 'bambu-studio', renderMode: RenderMode.Prerender },
  { path: 'creality-print', renderMode: RenderMode.Prerender },
  { path: 'orcaslicer', renderMode: RenderMode.Prerender },
  { path: 'snapmaker-orca', renderMode: RenderMode.Prerender },
  { path: 'anycubic-slicer', renderMode: RenderMode.Prerender },
  { path: 'elegoo-slicer', renderMode: RenderMode.Prerender },
  { path: 'qidi-studio', renderMode: RenderMode.Prerender },
  { path: 'orca-flashforge', renderMode: RenderMode.Prerender },
  { path: 'docs/getting-started', renderMode: RenderMode.Prerender },
  { path: 'docs/pro-subscription', renderMode: RenderMode.Prerender },
  { path: 'docs/prints', renderMode: RenderMode.Prerender },
  { path: 'docs/projects', renderMode: RenderMode.Prerender },
  { path: 'docs/materials', renderMode: RenderMode.Prerender },
  { path: 'docs/printers', renderMode: RenderMode.Prerender },
  { path: 'docs/analytics', renderMode: RenderMode.Prerender },
  { path: 'docs/android-app', renderMode: RenderMode.Prerender },
  { path: 'docs/cura-plugin', renderMode: RenderMode.Prerender },
  { path: 'docs/octoprint-webhook', renderMode: RenderMode.Prerender },
  { path: 'docs/klipper', renderMode: RenderMode.Prerender },
  { path: 'docs/slic3r-uploader', renderMode: RenderMode.Prerender },
  { path: 'docs/release-notes', renderMode: RenderMode.Prerender },
  { path: 'docs/about', renderMode: RenderMode.Prerender },
  { path: 'docs/privacy-policy', renderMode: RenderMode.Prerender },
  { path: '**', renderMode: RenderMode.Client },
];
