import { Injectable } from '@angular/core';
import { PrintImage } from '../../print.service';
import { GcodeParserBase } from '../core/gcode-parser-base';
import { GcodeSettings, SPACED_EQUALS } from '../core/gcode-settings';
import {
  buildOrcaFamilyNotes,
  ORCA_FAMILY_SETTING_KEYS,
} from '../orca/orca-notes';

@Injectable({
  providedIn: 'root',
})
export class AnycubicFileParserService extends GcodeParserBase {
  readonly slicerName = 'Anycubic Slicer';
  readonly settingsOptions = SPACED_EQUALS;
  readonly settingKeys = ORCA_FAMILY_SETTING_KEYS;

  detect(gcode: string): boolean {
    return /^\s*;\s*generated by AnycubicSlicer/m.test(gcode);
  }

  protected buildNotes(settings: GcodeSettings, gcode: string): string {
    return buildOrcaFamilyNotes(settings, gcode);
  }

  /** Anycubic writes "; print_time = 1h 2m 3s" instead of the Orca header line. */
  protected override parseEstimatedPrintTime(
    gcode: string,
    settings: GcodeSettings
  ): number | undefined {
    const printTime = settings.get('print_time');
    const seconds = printTime ? this.parseAsSeconds(printTime) : null;
    return seconds || super.parseEstimatedPrintTime(gcode, settings);
  }

  protected override parseImages(gcode: string): PrintImage[] {
    const image = gcode.match(
      /thumbnail begin[\sa-zA-Z\d]*([\S\s]*?); thumbnail end/im
    );
    if (!image?.[1]) {
      return [];
    }
    const base64Data = image[1]
      .trim()
      .replace(/;\s/g, '')
      .replace(/[\r\n]/g, '');
    return [
      {
        url: `data:image/png;base64,${base64Data}`,
        id: null,
        isDefault: true,
        displayOrder: 0,
      },
    ];
  }
}
