import { TestBed } from '@angular/core/testing';

import { AnycubicFileParserService } from './anycubic-file-parser.service';

describe('AnycubicFileParserService', () => {
  let service: AnycubicFileParserService;

  beforeEach(() => {
    TestBed.configureTestingModule({});
    service = TestBed.inject(AnycubicFileParserService);
  });

  it('should be created', () => {
    expect(service).toBeTruthy();
  });

  it('should parse the estimated print time using the normal mode when estimation exist in the gcode', async () => {
    const testGcode = `; HEADER_BLOCK_START
    ; generated by OrcaSlicer 1.7.0 on 2023-09-23 at 14:31:55
    ; model printing time: 1h 25m 2s; total estimated time: 1h 30m 53s
    ; total layer number: 22
    ; model label id: 89,109,129
    ; HEADER_BLOCK_END`;
    const expectedEstPrintTime = 5453;

    const actual = await service.parse(testGcode);

    expect(actual.estimatedPrintTimeInSeconds).toBe(expectedEstPrintTime);
  });

  it('should set the estimated print time to undefined when no estimations exist in the gcode', async () => {
    const testGcodeWithoutEstimations = `; total filament used [g] = 0.0
    ; total filament cost = 0.0`;

    const actual = await service.parse(testGcodeWithoutEstimations);

    expect(actual.estimatedPrintTimeInSeconds).toBeUndefined();
  });

  it('detects the AnycubicSlicer marker', () => {
    expect(service.detect('; generated by AnycubicSlicer 1.3.2')).toBeTrue();
  });

  it('extracts the embedded thumbnail as the default image', async () => {
    const gcode = `; generated by AnycubicSlicer 1.3.2
; thumbnail begin 48x48 100
; iVBORw0KGgo
; AAAA
; thumbnail end
; print_time = 1h 0m 0s`;
    const print = await service.parse(gcode);
    expect(print.images.length).toBe(1);
    expect(print.images[0].url).toBe('data:image/png;base64,iVBORw0KGgoAAAA');
    expect(print.images[0].isDefault).toBeTrue();
    expect(print.estimatedPrintTimeInSeconds).toBe(3600);
  });
});

describe('AnycubicFileParserService filament estimates', () => {
  let service: AnycubicFileParserService;

  beforeEach(() => {
    TestBed.configureTestingModule({});
    service = TestBed.inject(AnycubicFileParserService);
  });

  it('should return undefined when diameter or length is missing or zero', () => {
    const invalidInputs = [
      `; filament_type = PLA
; filament used [mm] = 1000`,
      `; filament_type = PLA
; filament_diameter = 1.75`,
      `; filament_type = PLA
; filament_diameter = 0
; filament used [mm] = 1000`,
      `; filament_type = PLA
; filament_diameter = 1.75
; filament used [mm] = 0`,
    ];

    invalidInputs.forEach((gcode) => {
      expect(service.estimateFilamentUsageInMg(gcode)).toBeUndefined();
    });
  });
});
