; Deliberately carries no slicer signature. `detectSlicerFromGcode` matches on
; markers like "generated by PrusaSlicer" or "generated by OrcaSlicer"; none of
; them appear here, so this file must take the unknown-slicer branch.

G21 ; set units to millimeters
G90 ; use absolute coordinates
G28 ; home all axes
G1 Z0.2 F720
G1 X10.0 Y10.0 E0.5 F1200
G1 X40.0 Y10.0 E1.6 F1200
G1 X40.0 Y40.0 E2.7 F1200
G1 X10.0 Y40.0 E3.8 F1200
M84 ; disable motors
