// Serializers that turn a docs manifest into the files Angular and the Node
// scripts consume. Everything here is a pure string function so the generated
// output is testable without touching the filesystem.

import { toChildRoutes, toServerRoutes } from './docs-manifest-lib.mjs';

export const BANNER = [
  '// DO NOT EDIT — generated by scripts/build-docs.mjs from src/content/docs/*.md.',
  '// Run `npm run docs:generate` after changing a doc source.',
].join('\n');

const HTML_BANNER =
  '<!-- DO NOT EDIT — generated by scripts/build-docs.mjs from src/content/docs. -->';

/**
 * @param {object} page an enriched manifest page
 * @returns {string|null} the component source, or null when the page keeps a
 *   hand-written component (the `component:` escape hatch)
 */
export function emitPageComponentTs(page) {
  if (page.component) return null;

  const fields = Object.entries(page.constants ?? {}).map(
    ([name, value]) => `  public readonly ${name} = ${literal(value)};`
  );

  return [
    BANNER,
    "import { ChangeDetectionStrategy, Component } from '@angular/core';",
    '',
    '@Component({',
    `  selector: '${page.selector}',`,
    `  templateUrl: './docs-${page.slug}.component.html',`,
    ...(page.hasStyles
      ? [`  styleUrls: ['./docs-${page.slug}.component.scss'],`]
      : []),
    '  standalone: false,',
    '  changeDetection: ChangeDetectionStrategy.OnPush,',
    '})',
    `export class ${page.className} {${fields.length ? `\n${fields.join('\n')}\n` : '\n'}}`,
    '',
  ].join('\n');
}

/** Wraps a generated template with its banner. */
// Every page the Markdown pipeline replaced opened with this wrapper, and the
// stylesheets still hang off it: styles.scss sets the docs body font size and
// min-height on `.docs-markdown`, and docs-getting-started.component.scss sets
// its max-width, centering and padding. It is structural, not content, so the
// generator emits it rather than asking each .md file to repeat it.
export function emitPageTemplate(template) {
  return `${HTML_BANNER}\n<div class="docs-markdown">\n${template}\n</div>\n`;
}

export function emitRoutesTs(manifest) {
  const routes = toChildRoutes(manifest);
  const routed = manifest.pages.filter(
    (p) => !p.dormant && routes.some((r) => r.component === p.className)
  );

  const imports = routed.map(
    (page) =>
      `import { ${page.className} } from '${page.component?.path ?? `./pages/docs-${page.slug}.component`}';`
  );

  const entries = routes.map((route) => {
    if (route.component) {
      return `  { path: '${route.path}', component: ${route.component} },`;
    }
    if (route.pathMatch) {
      return `  { path: '${route.path}', redirectTo: '${route.redirectTo}', pathMatch: '${route.pathMatch}' },`;
    }
    return `  { path: '${route.path}', redirectTo: '${route.redirectTo}' },`;
  });

  return [
    BANNER,
    "import { Routes } from '@angular/router';",
    '',
    ...imports,
    '',
    'export const DOCS_ROUTES: Routes = [',
    ...entries,
    '];',
    '',
  ].join('\n');
}

/**
 * The generated page components, for DocumentationModule's `declarations`.
 *
 * They stay `standalone: false` on purpose: a routed standalone component would
 * not inherit RouterModule/MatIcon/YouTubePlayer from the module, and
 * `strictTemplates` turns a missing directive into a build error rather than
 * inert markup. A `component:` page is already declared by hand, so it is left
 * out — declaring it twice would not compile.
 */
export function emitDeclarationsTs(manifest) {
  const generated = manifest.pages.filter((p) => !p.dormant && !p.component);

  return [
    BANNER,
    ...generated.map(
      (page) =>
        `import { ${page.className} } from './pages/docs-${page.slug}.component';`
    ),
    '',
    'export const DOCS_PAGE_COMPONENTS = [',
    ...generated.map((page) => `  ${page.className},`),
    '];',
    '',
  ].join('\n');
}

export function emitServerRoutesTs(manifest) {
  const entries = toServerRoutes(manifest).map(
    (route) =>
      `  { path: '${route.path}', renderMode: RenderMode.${route.renderMode} },`
  );

  return [
    BANNER,
    "import { RenderMode, ServerRoute } from '@angular/ssr';",
    '',
    'export const DOCS_SERVER_ROUTES: ServerRoute[] = [',
    ...entries,
    '];',
    '',
  ].join('\n');
}

export function emitManifestTs() {
  return [
    BANNER,
    "import manifest from './docs-manifest.json';",
    '',
    'export interface DocManifestPage {',
    '  readonly slug: string;',
    '  readonly path: string;',
    '  readonly title: string;',
    '  readonly description: string;',
    '  readonly navLabel: string;',
    '  readonly group: string;',
    '  readonly order: number;',
    '  readonly mode: string;',
    '  readonly updated: string;',
    '  readonly related: readonly string[];',
    '  readonly aliases: readonly string[];',
    '  readonly dormant: boolean;',
    '  readonly className: string;',
    '  readonly selector: string;',
    '}',
    '',
    'export const DOC_PAGES: readonly DocManifestPage[] =',
    '  manifest.pages as readonly DocManifestPage[];',
    '',
  ].join('\n');
}

/**
 * @param {object} manifest
 * @param {Record<string, string>} templates rendered template per slug
 */
export function emitSearchIndexJson(manifest, templates) {
  const entries = manifest.pages
    .filter((page) => !page.dormant)
    .map((page) => {
      const template = templates[page.slug] ?? '';
      return {
        path: page.path,
        title: page.title,
        navLabel: page.navLabel,
        group: page.group,
        headings: headingsOf(template),
        text: plainText(template),
      };
    });

  return `${JSON.stringify(entries, null, 2)}\n`;
}

export function emitFiguresTs(manifest, templates) {
  const entries = manifest.pages
    .filter((page) => !page.dormant)
    .map((page) => {
      const figures = figuresOf(templates[page.slug] ?? '')
        .map(
          (figure) =>
            `    { src: '${escapeSingle(figure.src)}', alt: '${escapeSingle(figure.alt)}' },`
        )
        .join('\n');
      return `  '${page.path}': [\n${figures}${figures ? '\n' : ''}  ],`;
    });

  return [
    BANNER,
    'export interface DocFigure {',
    '  readonly src: string;',
    '  readonly alt: string;',
    '}',
    '',
    'export const DOC_FIGURES: Record<string, readonly DocFigure[]> = {',
    ...entries,
    '};',
    '',
  ].join('\n');
}

function headingsOf(template) {
  const headings = [];
  for (const match of template.matchAll(
    /<h[1-6]([^>]*)>([\s\S]*?)<\/h[1-6]>/g
  )) {
    const id = /\sid="([^"]+)"/.exec(match[1]);
    const text = plainText(match[2]);
    headings.push(id ? `${text}#${id[1]}` : text);
  }
  return headings;
}

function figuresOf(template) {
  const figures = [];
  for (const match of template.matchAll(/<img\b([^>]*)>/g)) {
    const src = /\ssrc="([^"]*)"/.exec(match[1]);
    const alt = /\salt="([^"]*)"/.exec(match[1]);
    if (src) figures.push({ src: src[1], alt: alt ? alt[1] : '' });
  }
  return figures;
}

function plainText(template) {
  return (
    template
      .replace(/<pre[\s\S]*?<\/pre>/g, ' ')
      .replace(/<[^>]+>/g, ' ')
      .replace(/&mdash;/g, '—')
      .replace(/&lt;/g, '<')
      .replace(/&gt;/g, '>')
      .replace(/&nbsp;/g, ' ')
      // `&amp;` is unescaped last. Doing it first would turn an authored
      // `&amp;lt;` into `&lt;` and then into `<`, inventing markup the source
      // deliberately escaped.
      .replace(/&amp;/g, '&')
      .replace(/\s+/g, ' ')
      // Stripping an inline tag such as <strong> leaves a gap before the
      // punctuation that followed it, which would break phrase matching.
      .replace(/\s+([.,;:!?)\]])/g, '$1')
      .trim()
  );
}

/**
 * Renders a frontmatter constant as TypeScript. A value containing `${` is a
 * template literal by intent — that is how `docs-mcp` composes one constant out
 * of two others — so it is emitted with backticks rather than escaped.
 */
function literal(value) {
  if (typeof value === 'number' || typeof value === 'boolean')
    return String(value);
  const text = String(value);
  // Backslashes are escaped before backticks: an unescaped trailing `\` would
  // otherwise consume the closing backtick and break out of the literal.
  if (text.includes('${'))
    return `\`${text.replace(/\\/g, '\\\\').replace(/`/g, '\\`')}\``;
  return `'${escapeSingle(text)}'`;
}

function escapeSingle(text) {
  return text.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}
