// Serializers that turn a docs manifest into the files Angular and the Node
// scripts consume. Everything here is a pure string function so the generated
// output is testable without touching the filesystem.

import {
  RELEASE_NOTES_SLUG,
  toChildRoutes,
  toServerRoutes,
} from './docs-manifest-lib.mjs';

export const BANNER = [
  '// DO NOT EDIT — generated by scripts/build-docs.mjs from src/content/docs/*.md.',
  '// Run `npm run docs:generate` after changing a doc source.',
].join('\n');

const HTML_BANNER =
  '<!-- DO NOT EDIT — generated by scripts/build-docs.mjs from src/content/docs. -->';

/**
 * @param {object} page an enriched manifest page
 * @returns {string|null} the component source, or null when the page keeps a
 *   hand-written component (the `component:` escape hatch)
 */
export function emitPageComponentTs(page) {
  if (page.component) return null;

  const fields = Object.entries(page.constants ?? {}).map(
    ([name, value]) => `  public readonly ${name} = ${literal(value)};`
  );

  return [
    BANNER,
    "import { ChangeDetectionStrategy, Component } from '@angular/core';",
    '',
    '@Component({',
    `  selector: '${page.selector}',`,
    `  templateUrl: './docs-${page.slug}.component.html',`,
    ...(page.hasStyles
      ? [`  styleUrls: ['./docs-${page.slug}.component.scss'],`]
      : []),
    '  standalone: false,',
    '  changeDetection: ChangeDetectionStrategy.OnPush,',
    '})',
    `export class ${page.className} {${fields.length ? `\n${fields.join('\n')}\n` : '\n'}}`,
    '',
  ].join('\n');
}

/** Wraps a generated template with its banner. */
// Every page the Markdown pipeline replaced opened with this wrapper, and the
// stylesheets still hang off it: styles.scss sets the docs body font size and
// min-height on `.docs-markdown`, and docs-getting-started.component.scss sets
// its max-width, centering and padding. It is structural, not content, so the
// generator emits it rather than asking each .md file to repeat it.
export function emitPageTemplate(template) {
  return `${HTML_BANNER}\n<div class="docs-markdown">\n${template}\n</div>\n`;
}

export function emitRoutesTs(manifest) {
  const routes = toChildRoutes(manifest);
  const routed = manifest.pages.filter(
    (p) => !p.dormant && routes.some((r) => r.component === p.className)
  );

  const imports = routed.map(
    (page) =>
      `import { ${page.className} } from '${page.component?.path ?? `./pages/docs-${page.slug}.component`}';`
  );

  const entries = routes.map((route) => {
    if (route.component) {
      return `  { path: '${route.path}', component: ${route.component} },`;
    }
    if (route.pathMatch) {
      return `  { path: '${route.path}', redirectTo: '${route.redirectTo}', pathMatch: '${route.pathMatch}' },`;
    }
    return `  { path: '${route.path}', redirectTo: '${route.redirectTo}' },`;
  });

  return [
    BANNER,
    "import { Routes } from '@angular/router';",
    '',
    ...imports,
    '',
    'export const DOCS_ROUTES: Routes = [',
    ...entries,
    '];',
    '',
  ].join('\n');
}

/**
 * The generated page components, for DocumentationModule's `declarations`.
 *
 * They stay `standalone: false` on purpose: a routed standalone component would
 * not inherit RouterModule/MatIcon/YouTubePlayer from the module, and
 * `strictTemplates` turns a missing directive into a build error rather than
 * inert markup. A `component:` page is already declared by hand, so it is left
 * out — declaring it twice would not compile.
 */
export function emitDeclarationsTs(manifest) {
  const generated = manifest.pages.filter((p) => !p.dormant && !p.component);

  return [
    BANNER,
    ...generated.map(
      (page) =>
        `import { ${page.className} } from './pages/docs-${page.slug}.component';`
    ),
    '',
    'export const DOCS_PAGE_COMPONENTS = [',
    ...generated.map((page) => `  ${page.className},`),
    '];',
    '',
  ].join('\n');
}

export function emitServerRoutesTs(manifest) {
  const entries = toServerRoutes(manifest).map(
    (route) =>
      `  { path: '${route.path}', renderMode: RenderMode.${route.renderMode} },`
  );

  return [
    BANNER,
    "import { RenderMode, ServerRoute } from '@angular/ssr';",
    '',
    'export const DOCS_SERVER_ROUTES: ServerRoute[] = [',
    ...entries,
    '];',
    '',
  ].join('\n');
}

export function emitManifestTs() {
  return [
    BANNER,
    "import manifest from './docs-manifest.json';",
    '',
    'export interface DocManifestPage {',
    '  readonly slug: string;',
    '  readonly path: string;',
    '  readonly title: string;',
    '  readonly description: string;',
    '  readonly navLabel: string;',
    '  readonly group: string;',
    '  readonly order: number;',
    '  readonly mode: string;',
    '  readonly updated: string;',
    '  readonly related: readonly string[];',
    '  readonly aliases: readonly string[];',
    '  readonly dormant: boolean;',
    '  readonly className: string;',
    '  readonly selector: string;',
    '}',
    '',
    'export const DOC_PAGES: readonly DocManifestPage[] =',
    '  manifest.pages as readonly DocManifestPage[];',
    '',
    '/**',
    ' * One entry per release, newest first.',
    ' *',
    ' * `anchor` is derived from `version`, not from the heading text, and is the',
    ' * published deep link (`/docs/release-notes#v1.38.0`). It is a contract:',
    ' * validate-docs fails if a previously published one stops being emitted.',
    ' */',
    'export interface DocRelease {',
    '  readonly version: string;',
    '  readonly date: string;',
    '  readonly title: string;',
    '  readonly anchor: string;',
    '  readonly highlights: readonly string[];',
    '  /** True when the page does not render this release and the archive does. */',
    '  readonly archived: boolean;',
    '}',
    '',
    'export const DOC_RELEASES: readonly DocRelease[] =',
    '  manifest.releases as readonly DocRelease[];',
    '',
  ].join('\n');
}

/**
 * The search index: one entry per heading SECTION, not per page.
 *
 * Page-level entries would be useless on exactly the pages a reader most needs
 * help with. `docs/release-notes` alone is 78 KB of prose under 155 headings —
 * a hit on it says "the answer is somewhere in the changelog". A section entry
 * instead names the heading it matched and deep-links to that heading's anchor.
 *
 * Sections are cut at h1-h3. h4 and below stay inside their parent: "Full List
 * of Changes:" appears under every one of the 99 releases and would fragment
 * each of them into a section whose title says nothing.
 *
 * @param {object} manifest
 * @param {Record<string, string>} templates rendered template per slug
 */
export function emitSearchIndexJson(manifest, templates) {
  const entries = [];

  for (const page of manifest.pages.filter((p) => !p.dormant)) {
    for (const section of sectionsOf(templates[page.slug] ?? '', page)) {
      entries.push(section);
    }
  }

  return `${JSON.stringify(entries, null, 2)}\n`;
}

/** Sections are cut at these levels; deeper headings stay with their parent. */
const SECTION_HEADING = /<h([1-3])([^>]*)>([\s\S]*?)<\/h\1\s*>/g;

/**
 * Splits one rendered page into searchable sections.
 *
 * @param {string} template
 * @param {{ path: string, navLabel: string, group: string,
 *   constants?: Record<string, string> }} page
 * @returns {object[]}
 */
export function sectionsOf(template, page) {
  // Before `plainText`, which decodes `&#123;`/`&#125;` — the escapes an author
  // writes to SHOW a brace. Resolving after that step would treat those as
  // bindings and substitute into text that deliberately escaped itself.
  const source = resolveBindings(stripComments(template), page.constants);

  const headings = [];
  for (const match of source.matchAll(SECTION_HEADING)) {
    const id = /\sid="([^"]+)"/.exec(match[2]);
    headings.push({
      title: plainText(match[3]),
      anchor: id ? id[1] : null,
      at: match.index,
      after: match.index + match[0].length,
    });
  }

  const sections = [];

  // Anything before the first heading belongs to the page itself. It is titled
  // with the nav label rather than left blank, so a hit there still names
  // something the reader recognises from the sidebar.
  const lead = plainText(
    source.slice(0, headings.length ? headings[0].at : source.length),
    { keepCode: true }
  );
  if (lead) {
    sections.push({ title: page.navLabel, anchor: null, text: lead });
  }

  headings.forEach((heading, i) => {
    const body = source.slice(
      heading.after,
      i + 1 < headings.length ? headings[i + 1].at : source.length
    );
    sections.push({
      title: heading.title,
      anchor: heading.anchor,
      text: plainText(body, { keepCode: true }),
    });
  });

  return sections.map((section, ordinal) => ({
    // Ordinal, not the anchor: a section is indexed whether or not its heading
    // declares one, and MiniSearch needs an id for every document.
    id: `${page.path}::${ordinal}`,
    path: page.path,
    url: section.anchor ? `/${page.path}#${section.anchor}` : `/${page.path}`,
    title: section.title,
    page: page.navLabel,
    group: page.group,
    text: section.text,
  }));
}

/**
 * The per-page table of contents, one entry per h2-h4 that carries an id.
 *
 * Built here rather than scraped from the DOM at runtime for two reasons: the
 * docs are prerendered, so the TOC has to exist in the static HTML a crawler
 * (and a reader with a cold cache) sees; and scraping would tie the outline to
 * whichever page happens to be mounted, which is exactly the coupling the
 * generated manifest exists to avoid.
 *
 * `release-notes` is excluded deliberately. Its page paints ten releases and
 * lazily imports the other ninety-odd, so most of its 155 headings are not in
 * the DOM on arrival — a TOC over them would be a list of dead links, and a
 * 155-entry rail is not navigation anyway.
 *
 * @param {object} manifest
 * @param {Record<string, string>} templates rendered template per slug
 */
export function emitOutlineTs(manifest, templates) {
  const entries = manifest.pages
    .filter((page) => !page.dormant && page.slug !== RELEASE_NOTES_SLUG)
    .map((page) => {
      const headings = outlineOf(templates[page.slug] ?? '')
        .map(
          (heading) =>
            `    { id: '${escapeSingle(heading.id)}', ` +
            `text: '${escapeSingle(heading.text)}', depth: ${heading.depth} },`
        )
        .join('\n');
      return `  '${page.path}': [\n${headings}${headings ? '\n' : ''}  ],`;
    });

  return [
    BANNER,
    'export interface DocHeading {',
    '  /** The anchor to link to; always present, never derived at runtime. */',
    '  readonly id: string;',
    '  readonly text: string;',
    '  /** 1 for a top-level section, 2 for one nested under it. */',
    '  readonly depth: number;',
    '}',
    '',
    'export const DOC_OUTLINE: Record<string, readonly DocHeading[]> = {',
    ...entries,
    '};',
    '',
  ].join('\n');
}

/** Outline levels. h1 is a page title; h5 and h6 never reach the rail. */
const OUTLINE_HEADING = /<h([2-4])([^>]*)>([\s\S]*?)<\/h\1\s*>/g;

/**
 * One page's headings, normalized to display depths.
 *
 * @param {string} template
 * @returns {{ id: string, text: string, depth: number }[]}
 */
export function outlineOf(template) {
  const headings = [];
  for (const match of stripComments(template).matchAll(OUTLINE_HEADING)) {
    const id = /\sid="([^"]+)"/.exec(match[2]);
    const text = plainText(match[3]);
    // A heading with no id is not linkable. The generator gives every h2-h4 a
    // derived one, so in practice this only skips a heading whose text
    // slugified to nothing.
    if (id && text) headings.push({ id: id[1], text, level: Number(match[1]) });
  }

  const sections = withoutPageTitle(headings);
  if (sections.length === 0) return [];

  // Depth is relative, not absolute: a page whose sections are h2 (the privacy
  // policy) and one whose sections are h3 (every feature page) both start their
  // rail at depth 1, so the indentation means the same thing everywhere.
  const top = Math.min(...sections.map((h) => h.level));
  return sections.map(({ id, text, level }) => ({
    id,
    text,
    depth: level - top + 1,
  }));
}

/**
 * Drops the leading heading when it is the page's title rather than a section.
 *
 * Most pages open with a lone `## Printers` that repeats the nav label; listing
 * it as the first TOC entry is noise. But `privacy-policy` uses an `<h1>` title
 * and nine `<h2>` sections, so "the first heading is the title" is not a rule
 * that can be applied blindly. The test is that it stands ALONE at the
 * shallowest level — a page with nine peers at that level has no title among
 * them, because a title has no peers.
 */
function withoutPageTitle(headings) {
  if (headings.length === 0) return headings;

  const top = Math.min(...headings.map((h) => h.level));
  const atTop = headings.filter((h) => h.level === top);
  return atTop.length === 1 && headings[0].level === top
    ? headings.slice(1)
    : headings;
}

export function emitFiguresTs(manifest, templates) {
  const entries = manifest.pages
    .filter((page) => !page.dormant)
    .map((page) => {
      const figures = figuresOf(templates[page.slug] ?? '')
        .map(
          (figure) =>
            `    { src: '${escapeSingle(figure.src)}', alt: '${escapeSingle(figure.alt)}' },`
        )
        .join('\n');
      return `  '${page.path}': [\n${figures}${figures ? '\n' : ''}  ],`;
    });

  return [
    BANNER,
    'export interface DocFigure {',
    '  readonly src: string;',
    '  readonly alt: string;',
    '}',
    '',
    'export const DOC_FIGURES: Record<string, readonly DocFigure[]> = {',
    ...entries,
    '};',
    '',
  ].join('\n');
}

/**
 * The generated `name -> asset` map that `<doc-figure name="...">` resolves.
 *
 * Deliberately a SECOND artifact rather than a rewrite of docs-figures.ts: that
 * one is scraped OUT of authored markup, this one feeds INTO it. Merging them
 * would make one file mean two opposite things.
 *
 * Width and height travel with the src because `<doc-figure>` requires them —
 * an author who typed them by hand would be pinning a number that the next
 * recapture invalidates, and a wrong intrinsic size reflows the prose as the
 * image loads. Resolving all three from one name is the whole point.
 *
 * @param {Record<string, {light: object, dark: object}>} captures docs-captures.json
 */
export function emitCapturesTs(captures) {
  const image = (value) =>
    `{ src: '${escapeSingle(value.src)}', width: ${value.width}, height: ${value.height} }`;

  const entries = Object.keys(captures)
    .sort()
    .flatMap((name) => [
      `  '${escapeSingle(name)}': {`,
      `    light: ${image(captures[name].light)},`,
      `    dark: ${image(captures[name].dark)},`,
      '  },',
    ]);

  return [
    '// DO NOT EDIT — generated by scripts/build-docs.mjs from',
    '// src/content/docs-captures.json, which scripts/process-captures.mjs writes.',
    '// To change a figure, recapture it: `npm run capture:docs:all`.',
    'export interface DocCaptureImage {',
    '  readonly src: string;',
    '  readonly width: number;',
    '  readonly height: number;',
    '}',
    '',
    '/** Both themes are always present; see scripts/process-captures.lib.mjs. */',
    'export interface DocCapture {',
    '  readonly light: DocCaptureImage;',
    '  readonly dark: DocCaptureImage;',
    '}',
    '',
    'export const DOC_CAPTURES: Record<string, DocCapture> = {',
    ...entries,
    '};',
    '',
  ].join('\n');
}

/**
 * Commented-out markup is not on the page, so no projection may read it. It has
 * to go before any of the regexes below run: `<[^>]+>` stops at the first `>`,
 * so a comment wrapping a tag (`<!-- <img src="…"> …`) loses only the tag and
 * leaves the prose and the trailing `-->` behind as searchable text.
 */
function stripComments(template) {
  return template.replace(/<!--[\s\S]*?-->/g, ' ');
}

/**
 * An interpolated string literal, e.g. `{{' ...text... '}}`.
 *
 * Authors wrap a sample in one when the sample itself contains braces — the
 * Moonraker config on the Klipper page is Jinja, so `{% set %}` would otherwise
 * be parsed as Angular syntax. The reader sees the literal, so the index takes
 * the literal and drops the wrapper.
 *
 * The quote is matched by a negated class rather than a backreference so that
 * the scan cannot run past the closing quote: an expression such as
 * `{{ 'a' + 'b' }}` stops matching and is left alone rather than being
 * half-evaluated into `a' + 'b`, and an unclosed `{{'` cannot rescan the rest
 * of the document once per opening.
 */
const STRING_BINDING = /\{\{\s*(?:'([^']*)'|"([^"]*)")\s*\}\}/g;

/** An Angular binding to a single frontmatter constant, e.g. `{{ mcpEndpoint }}`. */
const CONSTANT_BINDING = /\{\{\s*([A-Za-z_$][\w$]*)\s*\}\}/g;

/** A constant referring to a sibling, e.g. `${this.mcpEndpoint}`. */
const CONSTANT_REFERENCE = /\$\{\s*this\.([A-Za-z_$][\w$]*)\s*\}/g;

/**
 * Substitutes what a template's interpolations render to.
 *
 * The reader sees the VALUE — `https://api.3dprintlog.com/mcp` — so that is
 * what the index has to hold. Left alone, the binding was stored verbatim:
 * the endpoint was unsearchable and any excerpt covering it showed a reader
 * the literal `{{ mcpEndpoint }}`.
 *
 * A binding with no matching constant is left as authored rather than dropped,
 * so a typo stays visible instead of silently emptying a section.
 *
 * @param {string} template
 * @param {Record<string, string> | undefined} constants
 */
function resolveBindings(template, constants) {
  const text = template.replace(
    STRING_BINDING,
    (_binding, single, double) =>
      // A space, not nothing: the wrapper often sits tight against the prose
      // before it, and dropping it outright would fuse two words together.
      ` ${escapeSubstitution(single ?? double)} `
  );

  if (!constants) {
    return text;
  }

  return text.replace(CONSTANT_BINDING, (binding, name) =>
    name in constants
      ? escapeSubstitution(constantValue(constants, name, new Set()))
      : binding
  );
}

/**
 * Re-encodes a substituted value so the pipeline reads it as text.
 *
 * What a binding renders is TEXT — Angular escapes it, so a reader who sees
 * `echo <your-api-key>` sees those angle brackets. Splicing the raw value back
 * into the template would hand it to the heading scanner and the tag stripper
 * instead: `<your-api-key>` vanished as though it were a tag, and a literal
 * `<h2 id="x">` opened a section that does not exist on the page.
 *
 * Numeric references, not `&lt;`, because `plainText` decodes those itself and
 * this has to survive whether or not a name is in its table.
 */
function escapeSubstitution(value) {
  return String(value)
    .replace(/&/g, '&#38;')
    .replace(/</g, '&#60;')
    .replace(/>/g, '&#62;');
}

/** One constant with its `${this.sibling}` references resolved. */
function constantValue(constants, name, seen) {
  if (seen.has(name)) {
    // Constants are authored by hand, so a cycle is a mistake rather than an
    // impossibility. Stop at the name instead of recursing forever.
    return `\${this.${name}}`;
  }
  seen.add(name);

  return String(constants[name]).replace(
    CONSTANT_REFERENCE,
    (reference, sibling) =>
      sibling in constants
        ? // A copy, not the same set: `seen` marks the chain currently being
          // resolved, so sharing one across siblings would read the SECOND
          // mention of a constant as a cycle and leave it unresolved.
          constantValue(constants, sibling, new Set(seen))
        : reference
  );
}

function headingsOf(template) {
  const headings = [];
  for (const match of stripComments(template).matchAll(
    /<h[1-6]([^>]*)>([\s\S]*?)<\/h[1-6]>/g
  )) {
    const id = /\sid="([^"]+)"/.exec(match[1]);
    const text = plainText(match[2]);
    headings.push(id ? `${text}#${id[1]}` : text);
  }
  return headings;
}

function figuresOf(template) {
  const figures = [];
  for (const match of stripComments(template).matchAll(/<img\b([^>]*)>/g)) {
    const src = /\ssrc="([^"]*)"/.exec(match[1]);
    const alt = /\salt="([^"]*)"/.exec(match[1]);
    if (src) figures.push({ src: src[1], alt: alt ? alt[1] : '' });
  }
  return figures;
}

/**
 * Character references the renderer emits, and their plain-text form. The
 * typographer produces the curly quotes and dashes; `&#64;`, `&#123;` and
 * `&#125;` are Angular escapes for `@`, `{` and `}`. Anything left encoded here
 * reaches the reader as literal `&rsquo;` in a search result.
 */
const CHARACTER_REFERENCES = {
  '&mdash;': '—',
  '&ndash;': '–',
  '&hellip;': '…',
  '&lsquo;': '‘',
  '&rsquo;': '’',
  '&ldquo;': '“',
  '&rdquo;': '”',
  '&quot;': '"',
  '&apos;': "'",
  '&lt;': '<',
  '&gt;': '>',
  '&nbsp;': ' ',
};

/**
 * @param {string} template
 * @param {{ keepCode?: boolean }} [options] `keepCode` indexes `<pre>` blocks
 *   rather than dropping them. The commands and endpoints on the integration
 *   pages are exactly what a reader searches for — `--callback-port` matched
 *   nothing while these were stripped. Headings and descriptions leave it off:
 *   a heading never contains a code block, and a meta description that opened
 *   with a shell command would read as noise.
 */
function plainText(template, { keepCode = false } = {}) {
  let text = stripComments(template);
  if (!keepCode) {
    text = text.replace(/<pre[\s\S]*?<\/pre>/g, ' ');
  }

  text = text
    .replace(/<[^>]+>/g, ' ')
    // Numeric references decode before the named ones so that `&amp;` stays
    // last: `&amp;#64;` is an authored literal and must not become `@`.
    .replace(/&#(\d+);/g, (_, code) => String.fromCodePoint(Number(code)));

  for (const [reference, character] of Object.entries(CHARACTER_REFERENCES)) {
    text = text.split(reference).join(character);
  }

  return (
    text
      // `&amp;` is unescaped last. Doing it first would turn an authored
      // `&amp;lt;` into `&lt;` and then into `<`, inventing markup the source
      // deliberately escaped.
      .replace(/&amp;/g, '&')
      .replace(/\s+/g, ' ')
      // Stripping an inline tag such as <strong> leaves a gap before the
      // punctuation that followed it, which would break phrase matching.
      .replace(/\s+([.,;:!?)\]])/g, '$1')
      .trim()
  );
}

/**
 * Renders a frontmatter constant as TypeScript. A value containing `${` is a
 * template literal by intent — that is how `docs-mcp` composes one constant out
 * of two others — so it is emitted with backticks rather than escaped.
 */
function literal(value) {
  if (typeof value === 'number' || typeof value === 'boolean')
    return String(value);
  const text = String(value);
  // Backslashes are escaped before backticks: an unescaped trailing `\` would
  // otherwise consume the closing backtick and break out of the literal.
  if (text.includes('${'))
    return `\`${text.replace(/\\/g, '\\\\').replace(/`/g, '\\`')}\``;
  return `'${escapeSingle(text)}'`;
}

function escapeSingle(text) {
  return text.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}
