import { PrintFilamentSourceMeasurement } from '../../print.service';
import { GcodeParserBase } from './gcode-parser-base';
import { GcodeSettings, SPACED_EQUALS } from './gcode-settings';
import { getTitleFromFileName, OTHER_FILAMENT } from './print-detail-defaults';

class TestParser extends GcodeParserBase {
  readonly slicerName = 'Test';
  readonly settingsOptions = SPACED_EQUALS;
  readonly settingKeys = [
    'layer_height',
    'wall_loops',
    'missing_one',
    'missing_two',
  ] as const;
  detect(gcode: string): boolean {
    return gcode.includes('generated by Test');
  }
  protected buildNotes(settings: GcodeSettings): string {
    return `LH=${settings.get('layer_height')}`;
  }
}

describe('GcodeParserBase', () => {
  let parser: TestParser;
  beforeEach(() => (parser = new TestParser()));

  describe('parse', () => {
    it('fills notes, file name and title', async () => {
      const print = await parser.parse(
        '; layer_height = 0.2',
        'my_cool-benchy.gcode'
      );
      expect(print.notes).toBe('LH=0.2');
      expect(print.fileName).toBe('my_cool-benchy.gcode');
      expect(print.title).toBe('My Cool Benchy');
    });

    it('reads "total estimated time:" from raw text', async () => {
      const print = await parser.parse('; total estimated time: 1h 30m 53s');
      expect(print.estimatedPrintTimeInSeconds).toBe(5453);
    });

    it('falls back to the PrusaSlicer normal-mode line', async () => {
      const print = await parser.parse(
        '; estimated printing time (normal mode) = 2h 1m 3s'
      );
      expect(print.estimatedPrintTimeInSeconds).toBe(7263);
    });

    it('leaves the time undefined when nothing matches', async () => {
      const print = await parser.parse('; nothing = here');
      expect(print.estimatedPrintTimeInSeconds).toBeUndefined();
    });
  });

  describe('getFilamentUsage', () => {
    it('emits one entry per non-zero slot with slot notes and per-slot weight', async () => {
      const print = await parser.parse(
        [
          '; filament used [mm] = 1234.56, 0.00, 567.80',
          '; filament used [g] = 3.68, 0.00, 1.69',
          '; filament_colour = #FF0000;#00FF00;#0000FF',
          '; filament_type = PLA;PLA;PETG',
        ].join('\n')
      );
      expect(print.filamentUsage.length).toBe(2);
      expect(print.filamentUsage[0]).toEqual(
        jasmine.objectContaining({
          id: null,
          filament: OTHER_FILAMENT,
          source: PrintFilamentSourceMeasurement.Length,
          estimatedSource: PrintFilamentSourceMeasurement.Length,
          estimatedLengthInM: 1.235,
          estimatedAmountMg: 3680,
          notes: 'Slot 1 · #FF0000 · PLA',
        })
      );
      expect(print.filamentUsage[1].estimatedLengthInM).toBe(0.568);
      expect(print.filamentUsage[1].estimatedAmountMg).toBe(1690);
      expect(print.filamentUsage[1].notes).toBe('Slot 3 · #0000FF · PETG');
      expect(print.estimatedFilamentUsageMg).toBeNull();
    });

    it('omits color and type from the note when absent', async () => {
      const print = await parser.parse('; filament used [mm] = 100');
      expect(print.filamentUsage[0].notes).toBe('Slot 1');
      expect(print.filamentUsage[0].estimatedAmountMg).toBeUndefined();
    });

    it('sets the legacy weight only when there are no per-slot rows', async () => {
      const print = await parser.parse('; filament used [g] = 12.5');
      expect(print.filamentUsage).toEqual([]);
      expect(print.estimatedFilamentUsageMg).toBe(12500);
    });
  });

  describe('estimateFilamentUsageInMg', () => {
    it('sums the reported gram slots', () => {
      expect(
        parser.estimateFilamentUsageInMg('; filament used [g] = 3.5, 1.5')
      ).toBe(5000);
    });

    it('prefers filament_density over the material table', () => {
      const mg = parser.estimateFilamentUsageInMg(
        '; filament_type = PLA\n; filament_diameter = 1.75\n; filament used [mm] = 1000\n; filament_density = 2'
      );
      // pi * 0.875^2 * 1000 mm^3 * 2 g/cm^3 = 4810.6 mg
      expect(mg).toBe(4810);
    });

    it('falls back to the material table by type, including Nylon', () => {
      const mg = parser.estimateFilamentUsageInMg(
        '; filament_type = Nylon\n; filament_diameter = 1.75\n; filament used [mm] = 1000'
      );
      expect(mg).toBe(2549);
    });

    it('returns undefined for an unknown material or missing diameter/length', () => {
      expect(
        parser.estimateFilamentUsageInMg(
          '; filament_type = TPU\n; filament_diameter = 1.75\n; filament used [mm] = 1000'
        )
      ).toBeUndefined();
      expect(
        parser.estimateFilamentUsageInMg(
          '; filament_type = PLA\n; filament used [mm] = 1000'
        )
      ).toBeUndefined();
      expect(
        parser.estimateFilamentUsageInMg(
          '; filament_type = PLA\n; filament_diameter = 0\n; filament used [mm] = 1000'
        )
      ).toBeUndefined();
      expect(
        parser.estimateFilamentUsageInMg(
          '; filament_type = PLA\n; filament_diameter = 1.75\n; filament used [mm] = 0'
        )
      ).toBeUndefined();
    });
  });

  describe('score', () => {
    it('is the fraction of settingKeys present', () => {
      const settings = GcodeSettings.parse(
        '; layer_height = 0.2\n; wall_loops = 2',
        SPACED_EQUALS
      );
      expect(parser.score(settings)).toBe(0.5);
    });

    it('is 0 for an empty index', () => {
      expect(parser.score(GcodeSettings.empty())).toBe(0);
    });
  });

  describe('getTitleFromFileName', () => {
    it('drops the gcode segment and capitalizes words, max 100 chars', () => {
      expect(getTitleFromFileName('benchy_v2.gcode')).toBe('Benchy V 2');
      expect(getTitleFromFileName('a'.repeat(150) + '.gcode').length).toBe(100);
    });
  });
});
