import parse from 'parse-duration';
import {
  PrintDetail,
  PrintFilamentSourceMeasurement,
  PrintFilamentSummaryDto,
  PrintImage,
} from '../../print.service';
import { GcodeNewPrintParser } from './gcode-new-print-parser';
import { GcodeSettings, GcodeSettingsOptions } from './gcode-settings';
import { trimGcodeWindow } from './gcode-window';
import { densityForMaterialType } from './material-densities';
import {
  createDefaultPrintDetail,
  getTitleFromFileName,
  OTHER_FILAMENT,
} from './print-detail-defaults';

/**
 * Shared behavior for every slicer parser: window the file, index its
 * settings once, then assemble a PrintDetail. Subclasses supply the slicer
 * marker, the separator style, the keys they read (which double as the
 * heuristic fingerprint) and the notes builder.
 */
export abstract class GcodeParserBase implements GcodeNewPrintParser {
  /** Display name used in the toast, telemetry and the "supported slicers" list. */
  abstract readonly slicerName: string;
  abstract readonly settingsOptions: GcodeSettingsOptions;
  /**
   * Every settings key this parser reads. The registry scores an unrecognized
   * file by the fraction of these keys it can resolve.
   */
  abstract readonly settingKeys: readonly string[];
  /** Exact marker match, e.g. "generated by OrcaSlicer". */
  abstract detect(gcode: string): boolean;
  protected abstract buildNotes(settings: GcodeSettings, gcode: string): string;

  protected readonly filamentLengthKey: string = 'filament used [mm]';
  protected readonly filamentWeightKey: string = 'filament used [g]';

  async parse(gcode: string, fileName?: string): Promise<PrintDetail> {
    const windowed = trimGcodeWindow(gcode);
    const settings = GcodeSettings.parse(windowed, this.settingsOptions);

    const print = createDefaultPrintDetail();
    print.estimatedPrintTimeInSeconds = this.parseEstimatedPrintTime(
      windowed,
      settings
    );
    print.filamentUsage = this.getFilamentUsage(settings);
    if (print.filamentUsage.length === 0) {
      // The legacy single-weight field only matters when there is no per-slot
      // breakdown; the edit form ignores it otherwise.
      print.estimatedFilamentUsageMg =
        this.estimateWeightInMg(settings) ?? null;
    }
    print.notes = this.buildNotes(settings, windowed);
    print.images = this.parseImages(windowed);

    if (fileName) {
      print.fileName = fileName;
      print.title = getTitleFromFileName(fileName);
    }

    return print;
  }

  /** Fraction (0..1) of settingKeys that resolve in the index. */
  score(settings: GcodeSettings): number {
    if (this.settingKeys.length === 0) {
      return 0;
    }
    const hits = this.settingKeys.filter((key) => settings.has(key)).length;
    return hits / this.settingKeys.length;
  }

  /** Convenience for specs and callers that hold raw gcode. */
  estimateFilamentUsageInMg(gcode: string): number | undefined {
    return this.estimateWeightInMg(
      GcodeSettings.parse(trimGcodeWindow(gcode), this.settingsOptions)
    );
  }

  protected parseEstimatedPrintTime(
    gcode: string,
    settings: GcodeSettings
  ): number | undefined {
    const totalEstimated = gcode.match(/total estimated time: (.+)$/im)?.[1];
    const candidates = [
      totalEstimated,
      settings.get('estimated printing time (normal mode)'),
      settings.get('estimated printing time (silent mode)'),
    ];
    for (const candidate of candidates) {
      const seconds = candidate ? this.parseAsSeconds(candidate) : null;
      if (seconds) {
        return seconds;
      }
    }
    return undefined;
  }

  protected getFilamentUsage(
    settings: GcodeSettings
  ): PrintFilamentSummaryDto[] {
    const lengthsMm = settings.getNumberList(this.filamentLengthKey);
    // The per-slot gram list has this name in every slicer; filamentWeightKey
    // (PrusaSlicer: the total) is only for the legacy single-weight estimate.
    const gramsBySlot = settings.getNumberList('filament used [g]');
    const colors = settings.getStringList('filament_colour');
    const types = settings.getStringList('filament_type');

    const usage: PrintFilamentSummaryDto[] = [];
    lengthsMm.forEach((mm, i) => {
      if (mm <= 0) {
        return;
      }
      const grams = gramsBySlot[i];
      usage.push({
        id: null,
        filament: OTHER_FILAMENT,
        source: PrintFilamentSourceMeasurement.Length,
        estimatedSource: PrintFilamentSourceMeasurement.Length,
        estimatedLengthInM: +(mm / 1000).toFixed(3),
        estimatedAmountMg: grams > 0 ? Math.round(grams * 1000) : undefined,
        notes: this.describeFilamentSlot(i, colors[i], types[i]),
      });
    });
    return usage;
  }

  /** "Slot 1 · #FF0000 · PLA" so the user can tell which spool each row is. */
  protected describeFilamentSlot(
    index: number,
    color?: string,
    type?: string
  ): string {
    const parts = [`Slot ${index + 1}`];
    if (color) parts.push(color);
    if (type) parts.push(type);
    return parts.join(' · ');
  }

  protected estimateWeightInMg(settings: GcodeSettings): number | undefined {
    const grams = settings
      .getNumberList(this.filamentWeightKey)
      .reduce((a, b) => a + b, 0);
    if (grams > 0) {
      return Math.round(grams * 1000);
    }

    const diameter = settings.getNumberList('filament_diameter')[0];
    if (!(diameter > 0)) {
      return undefined;
    }
    const lengthMm = settings.getNumberList(this.filamentLengthKey)[0];
    if (!(lengthMm > 0)) {
      return undefined;
    }

    // Slicers write the density the user configured, so prefer it over the table.
    const density =
      settings.getNumberList('filament_density')[0] ||
      densityForMaterialType(settings.getStringList('filament_type')[0] ?? '');
    if (!(density > 0)) {
      return undefined;
    }
    return this.calculateWeightInMg(density, lengthMm, diameter);
  }

  protected calculateWeightInMg(
    densityGPerCm3: number,
    lengthMm: number,
    diameterMm: number
  ): number {
    const radius = diameterMm / 2;
    const volumeMm3 = Math.PI * radius * radius * lengthMm;
    const grams = volumeMm3 * (densityGPerCm3 / 1000);
    return Math.floor(grams * 1000);
  }

  protected parseImages(_gcode: string): PrintImage[] {
    return [];
  }

  protected parseAsSeconds(input: string): number | null {
    if (input == null || input.trim() === '') {
      return null;
    }
    const ms = parse(input);
    return ms == null ? null : Math.floor(ms / 1000);
  }
}
