import { TestBed } from '@angular/core/testing';
import { ORCA_TWO_FILAMENT_GCODE } from '../fixtures/orca-two-filament.fixture';
import { PRUSA_MMU_TWO_SLOTS_GCODE } from '../fixtures/prusa-mmu-two-slots.fixture';
import { HEURISTIC_MATCH_THRESHOLD, SlicerRegistry } from './slicer-registry';

describe('SlicerRegistry', () => {
  let registry: SlicerRegistry;

  beforeEach(() => {
    TestBed.configureTestingModule({});
    registry = TestBed.inject(SlicerRegistry);
  });

  it('pins the threshold', () => {
    expect(HEURISTIC_MATCH_THRESHOLD).toBe(0.25);
  });

  it('lists parsers in detection order', () => {
    expect(registry.getSupportedSlicerNames()).toEqual([
      'Orca Slicer',
      'Bambu Studio',
      'Prusa Slicer',
      'Creality Print',
      'Anycubic Slicer',
      'Cura',
    ]);
  });

  it('resolves an exact marker as detected', () => {
    const result = registry.resolve(PRUSA_MMU_TWO_SLOTS_GCODE);
    expect(result.confidence).toBe('detected');
    expect(result.score).toBe(1);
    expect(result.parser?.slicerName).toBe('Prusa Slicer');
  });

  it('resolves a Snapmaker Orca export to the Orca parser by heuristic', () => {
    const snapmaker = ORCA_TWO_FILAMENT_GCODE.replace(
      'generated by OrcaSlicer 2.2.0',
      'generated by Snapmaker Orca 2.1.0'
    );
    const result = registry.resolve(snapmaker);
    expect(result.confidence).toBe('heuristic');
    expect(result.parser?.slicerName).toBe('Orca Slicer');
    expect(result.score).toBeGreaterThanOrEqual(HEURISTIC_MATCH_THRESHOLD);
  });

  it('breaks a tie in favor of the earlier entry (Orca over Bambu)', () => {
    // Same keys, same separators: identical scores.
    const result = registry.resolve(
      '; layer_height = 0.2\n; wall_loops = 2\n; sparse_infill_density = 15%\n; top_shell_layers = 4'
    );
    expect(result.parser?.slicerName).toBe('Orca Slicer');
  });

  it('resolves a bare Marlin file to none', () => {
    const result = registry.resolve('G28\nG1 X10 Y10 F3000\nG1 E5\nM104 S0');
    expect(result.confidence).toBe('none');
    expect(result.parser).toBeNull();
    expect(result.score).toBe(0);
  });
});
