import { TestBed } from '@angular/core/testing';
import { ORCA_TWO_FILAMENT_GCODE } from '../fixtures/orca-two-filament.fixture';
import { PRUSA_MMU_TWO_SLOTS_GCODE } from '../fixtures/prusa-mmu-two-slots.fixture';
import {
  HEURISTIC_MATCH_THRESHOLD,
  HEURISTIC_MIN_KEY_HITS,
  SlicerRegistry,
} from './slicer-registry';

describe('SlicerRegistry', () => {
  let registry: SlicerRegistry;

  beforeEach(() => {
    TestBed.configureTestingModule({});
    registry = TestBed.inject(SlicerRegistry);
  });

  it('pins the threshold and minimum hits', () => {
    expect(HEURISTIC_MATCH_THRESHOLD).toBe(0.25);
    expect(HEURISTIC_MIN_KEY_HITS).toBe(2);
  });

  it('lists parsers in detection order', () => {
    expect(registry.getSupportedSlicerNames()).toEqual([
      'Orca Slicer',
      'Bambu Studio',
      'Prusa Slicer',
      'Anycubic Slicer',
      'Cura',
      'Creality Print',
    ]);
  });

  it('resolves an exact marker as detected', () => {
    const result = registry.resolve(PRUSA_MMU_TWO_SLOTS_GCODE);
    expect(result.confidence).toBe('detected');
    expect(result.score).toBe(1);
    expect(result.parser?.slicerName).toBe('Prusa Slicer');
  });

  it('resolves a Snapmaker Orca export to the Orca parser by heuristic', () => {
    const snapmaker = ORCA_TWO_FILAMENT_GCODE.replace(
      'generated by OrcaSlicer 2.2.0',
      'generated by Snapmaker Orca 2.1.0'
    );
    const result = registry.resolve(snapmaker);
    expect(result.confidence).toBe('heuristic');
    expect(result.parser?.slicerName).toBe('Orca Slicer');
    expect(result.score).toBeGreaterThanOrEqual(HEURISTIC_MATCH_THRESHOLD);
  });

  it('breaks a tie in favor of the earlier entry (Orca over Bambu)', () => {
    // Same keys, same separators: identical scores.
    const result = registry.resolve(
      '; layer_height = 0.2\n; wall_loops = 2\n; sparse_infill_density = 15%\n; top_shell_layers = 4'
    );
    expect(result.parser?.slicerName).toBe('Orca Slicer');
  });

  it('does not let a single generic header line pick a parser', () => {
    const result = registry.resolve(`;FLAVOR:Marlin
G28
G1 X10 Y10 E5 F1200`);
    expect(result.confidence).toBe('none');
    expect(result.parser).toBeNull();
  });

  it('prefers Cura over Creality Print for a marker-less Cura-style header', () => {
    const result = registry.resolve(`;FLAVOR:Marlin
;TIME:669
;Filament used: 0.83m
;Layer height: 0.2
;MINX:1
;MAXZ:5`);
    expect(result.confidence).toBe('heuristic');
    expect(result.parser?.slicerName).toBe('Cura');
  });

  it('only honors a slicer marker at the start of a comment line', () => {
    const prusaWithNote = PRUSA_MMU_TWO_SLOTS_GCODE.replace(
      '; external perimeters extrusion width = 0.45mm',
      '; note = profile originally generated by OrcaSlicer 2.1'
    );
    expect(registry.resolve(prusaWithNote).parser?.slicerName).toBe(
      'Prusa Slicer'
    );
  });

  it('resolves a bare Marlin file to none', () => {
    const result = registry.resolve('G28\nG1 X10 Y10 F3000\nG1 E5\nM104 S0');
    expect(result.confidence).toBe('none');
    expect(result.parser).toBeNull();
    expect(result.score).toBe(0);
  });
});
