import { TestBed } from '@angular/core/testing';
import { BambuStudioFileParserService } from './bambu-studio-file-parser.service';

describe('BambuStudioFileParserService', () => {
  let service: BambuStudioFileParserService;

  beforeEach(() => {
    TestBed.configureTestingModule({});
    service = TestBed.inject(BambuStudioFileParserService);
  });

  it('detects the Bambu Studio header', () => {
    expect(
      service.detect('; BambuStudio 01.10.01.50\n; model printing time: 1h')
    ).toBeTrue();
    expect(service.detect('; generated by OrcaSlicer 2.2.0')).toBeFalse();
  });

  it('parses time, per-slot usage and Orca-family notes', async () => {
    const gcode = `; BambuStudio 01.10.01.50
; model printing time: 30m 0s; total estimated time: 35m 10s
; filament used [mm] = 500.00, 250.00
; filament_type = PLA;PLA
; layer_height = 0.16
; wall_loops = 3
; support_filament = 0`;

    const print = await service.parse(gcode, 'toy.gcode');

    expect(print.estimatedPrintTimeInSeconds).toBe(2110);
    expect(print.filamentUsage.map((f) => f.estimatedLengthInM)).toEqual([
      0.5, 0.25,
    ]);
    expect(print.notes).toBe(`Print Settings:
Layer Height: 0.16mm
Walls: 3
Support: No Supports`);
    expect(print.title).toBe('Toy');
  });
});
