import { TestBed } from '@angular/core/testing';

import { OrcaFileParserService } from './orca-file-parser.service';
import { ORCA_TWO_FILAMENT_GCODE } from '../fixtures/orca-two-filament.fixture';

describe('OrcaFileParserService', () => {
  let service: OrcaFileParserService;

  beforeEach(() => {
    TestBed.configureTestingModule({});
    service = TestBed.inject(OrcaFileParserService);
  });

  it('should be created', () => {
    expect(service).toBeTruthy();
  });

  it('should parse the estimated print time using the normal mode when estimation exist in the gcode', async () => {
    const testGcode = `; HEADER_BLOCK_START
    ; generated by OrcaSlicer 1.7.0 on 2023-09-23 at 14:31:55
    ; model printing time: 1h 25m 2s; total estimated time: 1h 30m 53s
    ; total layer number: 22
    ; model label id: 89,109,129
    ; HEADER_BLOCK_END`;
    const expectedEstPrintTime = 5453;

    const actual = await service.parse(testGcode);

    expect(actual.estimatedPrintTimeInSeconds).toBe(expectedEstPrintTime);
  });

  it('should set the estimated print time to undefined when no estimations exist in the gcode', async () => {
    const testGcodeWithoutEstimations = `; total filament used [g] = 0.0
    ; total filament cost = 0.0`;

    const actual = await service.parse(testGcodeWithoutEstimations);

    expect(actual.estimatedPrintTimeInSeconds).toBeUndefined();
  });

  describe('estimateFilamentUsageInMg', () => {
    it('should return undefined when diameter or length is missing or zero', () => {
      const invalidInputs = [
        `; filament_type = PLA
; filament used [mm] = 1000`,
        `; filament_type = PLA
; filament_diameter = 1.75`,
        `; filament_type = PLA
; filament_diameter = 0
; filament used [mm] = 1000`,
        `; filament_type = PLA
; filament_diameter = 1.75
; filament used [mm] = 0`,
      ];

      invalidInputs.forEach((gcode) => {
        expect(service.estimateFilamentUsageInMg(gcode)).toBeUndefined();
      });
    });
  });
});

describe('OrcaFileParserService multi-filament', () => {
  let service: OrcaFileParserService;

  beforeEach(() => {
    TestBed.configureTestingModule({});
    service = TestBed.inject(OrcaFileParserService);
  });

  it('emits one usage row per used slot', async () => {
    const print = await service.parse(ORCA_TWO_FILAMENT_GCODE, 'cube.gcode');
    expect(print.filamentUsage.length).toBe(2);
    expect(print.filamentUsage[0].estimatedLengthInM).toBe(1.235);
    expect(print.filamentUsage[0].notes).toBe('Slot 1 · #FF0000 · PLA');
    expect(print.filamentUsage[1].estimatedLengthInM).toBe(0.568);
    expect(print.filamentUsage[1].notes).toBe('Slot 3 · #0000FF · PETG');
    expect(print.estimatedPrintTimeInSeconds).toBe(3723);
    expect(print.title).toBe('Cube');
  });

  it('keeps the notes text unchanged', async () => {
    const print = await service.parse(ORCA_TWO_FILAMENT_GCODE);
    expect(print.notes).toBe(`Print Settings:
Print Setting Config: 0.20mm Standard @BBL X1C
Printer Config: Bambu Lab X1 Carbon 0.4 nozzle
Layer Count: 50
Layer Height: 0.2mm
Top Layer Count: 4
Bottom Layer Count: 3
Walls: 2
Infill: 15%
Infill Pattern: grid
Support: No Supports`);
  });

  it('detects the OrcaSlicer marker', () => {
    expect(service.detect('; generated by OrcaSlicer 2.2.0 on')).toBeTrue();
    expect(service.detect('; generated by PrusaSlicer 2.9')).toBeFalse();
  });
});
