import { Injectable } from '@angular/core';
import { GcodeParserBase } from '../core/gcode-parser-base';
import { GcodeSettings, SPACED_EQUALS } from '../core/gcode-settings';
import { buildOrcaFamilyNotes, ORCA_FAMILY_SETTING_KEYS } from './orca-notes';

@Injectable({
  providedIn: 'root',
})
export class OrcaFileParserService extends GcodeParserBase {
  readonly slicerName = 'Orca Slicer';
  readonly settingsOptions = SPACED_EQUALS;
  readonly settingKeys = ORCA_FAMILY_SETTING_KEYS;

  detect(gcode: string): boolean {
    return /generated by OrcaSlicer/.test(gcode);
  }

  protected buildNotes(settings: GcodeSettings, gcode: string): string {
    return buildOrcaFamilyNotes(settings, gcode);
  }
}
